Repository paritytech/cumulus, pull requests merged in 2020-07, with the labels that each got.

#137 Script to register a parachain
  scripts/register_parachain.sh
Labels: A0-pleasereview

#139 Upgrade Polkadot & Substrate
  Cargo.lock
  test/parachain/src/command.rs
  test/parachain/src/service.rs
Labels: A0-pleasereview

#156 Harden storage against re-entry
  runtime/src/validate_block/implementation.rs
Labels: A0-pleasereview

#158 Fix storage_append
  runtime/src/validate_block/implementation.rs
Labels: A8-looksgood

#163 Fix Polkadot CLI arguments not properly parsed
  test/parachain/src/command.rs
  test/parachain/src/service.rs
Labels: F2-bug 🐜
