Repository paritytech/cumulus, pull requests merged in 2021-08, with the labels that each got.

#566 Companion to #9514 (Remove Filter and use Contains instead)
  Cargo.lock
  pallets/collator-selection/src/mock.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/xcmp-queue/src/mock.rs
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint-common/src/impls.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  primitives/utility/src/lib.rs
  test/runtime/src/lib.rs
Labels: A0-pleasereview

#567 CI: fix gh doc publishing
  .github/workflows/docs.yml
Labels: A3-inprogress, B0-patchthis, F2-bug 🐜

#568 WIP: docs: optimize docs build
  .github/workflows/docs.yml
Labels: A3-inprogress, B0-patchthis

#569 docs: undebug docs build
  .github/workflows/docs.yml
Labels: A0-pleasereview, B0-patchthis

#570 Use new MultiLocation syntax everywhere
  Cargo.lock
  pallets/dmp-queue/src/lib.rs
  pallets/xcm/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  polkadot-parachains/pallets/ping/src/lib.rs
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  primitives/utility/src/lib.rs
  test/service/src/lib.rs
Labels: A0-pleasereview

#576 remove lightSyncState field from chain specs
  polkadot-parachains/res/statemine.json
  polkadot-parachains/res/statemine_genesis.json
  polkadot-parachains/res/statemint.json
  polkadot-parachains/res/tick.json
  polkadot-parachains/res/track.json
  polkadot-parachains/res/trick.json
  polkadot-parachains/res/westmint.json
  polkadot-parachains/res/westmint_genesis.json
Labels: A0-pleasereview, B0-patchthis

#575 Remove `lightSyncState` Field from Chain Specs
  polkadot-parachains/res/statemine.json
  polkadot-parachains/res/statemine_genesis.json
  polkadot-parachains/res/statemint.json
  polkadot-parachains/res/tick.json
  polkadot-parachains/res/track.json
  polkadot-parachains/res/trick.json
  polkadot-parachains/res/westmint.json
  polkadot-parachains/res/westmint_genesis.json
Labels: A0-pleasereview, B0-patchthis

#578 Bump Spec on Statemine/Westmint
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B1-releasenotes

#579 Bump Spec Statemine/Westmint
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B1-releasenotes

#571 Companion for #3629 (XCM v2)
  .gitignore
  Cargo.lock
  pallets/dmp-queue/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  polkadot-parachains/pallets/ping/src/lib.rs
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  primitives/utility/src/lib.rs
Labels: A0-pleasereview

#592 Bump Tokio to 1.10
  Cargo.lock
  client/consensus/common/Cargo.toml
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  polkadot-parachains/Cargo.toml
  test/service/Cargo.toml
Labels: A2-insubstantial
