Repository paritytech/cumulus, pull requests merged in 2021-11, with the labels that each got.

#716 Bump subwasm version
  .github/workflows/srtool.yml
Labels: A2-insubstantial, A0-pleasereview, M1-ci

#718 Ensure a bad datastream cannot cause problems (#701)
  pallets/dmp-queue/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/tests.rs
Labels: A0-pleasereview, B0-patchthis

#726 Remove randomness collective flip new
  Cargo.lock
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo/Cargo.toml
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
  test/runtime-upgrade/Cargo.toml
  test/runtime/Cargo.toml
  test/runtime/src/lib.rs
Labels: M5-statemint

#735 Adjust XCM weights to 1B
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: M5-statemint

#731 Align Call Indices between Westmint and Statemint
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A3-inprogress, M5-statemint

#733 Bump Statemint Spec Version to 600
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: M5-statemint

#736 Align the Statemint Runtimes
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: M5-statemint

#742 Bump spec versions
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent

#740 polkadot collator builder
  README.md
  docker/polkadot-collator_builder.Containerfile
  docker/test-parachain-collator.dockerfile
Labels: A0-pleasereview, B1-releasenotes

#747 Collator version bump
  Cargo.lock
  polkadot-parachains/Cargo.toml
Labels: A2-insubstantial, A0-pleasereview, B0-silent

#705 Tweaks from template downstream review #80
  client/cli/src/lib.rs
  client/network/tests/sync.rs
  client/pov-recovery/tests/pov_recovery.rs
  pallets/asset-tx-payment/src/tests.rs
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/mock.rs
  pallets/collator-selection/src/tests.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/validate_block/tests.rs
  parachain-template/README.md
  parachain-template/node/src/chain_spec.rs
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  parachain-template/node/src/main.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/cli.rs
  polkadot-parachains/src/command.rs
  primitives/core/src/lib.rs
  primitives/parachain-inherent/src/client_side.rs
  test/relay-sproof-builder/src/lib.rs
  test/service/src/chain_spec.rs
  test/service/tests/integration.rs
  test/service/tests/runtime_upgrade.rs
Labels: A2-insubstantial, F5-documentation 📄

#732 Companion to substrate #10196 - Add group name in task metrics
  Cargo.lock
  client/collator/src/lib.rs
  client/network/src/lib.rs
  client/service/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/src/service.rs
  test/service/Cargo.toml
Labels: A0-pleasereview

#756 Update for latests substrate & polkadot
  Cargo.lock
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  parachain-template/node/src/chain_spec.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/parachains-common/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/service.rs
  test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#749 Update field event variants
  Cargo.lock
  polkadot-parachains/parachains-common/src/impls.rs
Labels: B0-silent, C1-low 📌

#759 move to rust 2021
  client/cli/Cargo.toml
  client/collator/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/common/Cargo.toml
  client/consensus/relay-chain/Cargo.toml
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  client/service/Cargo.toml
  pallets/asset-tx-payment/Cargo.toml
  pallets/aura-ext/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/dmp-queue/Cargo.toml
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/proc-macro/Cargo.toml
  pallets/session-benchmarking/Cargo.toml
  pallets/xcm/Cargo.toml
  pallets/xcmp-queue/Cargo.toml
  parachain-template/node/Cargo.toml
  parachain-template/pallets/template/Cargo.toml
  parachain-template/runtime/Cargo.toml
  polkadot-parachains/Cargo.toml
  polkadot-parachains/pallets/parachain-info/Cargo.toml
  polkadot-parachains/pallets/ping/Cargo.toml
  polkadot-parachains/parachains-common/Cargo.toml
  polkadot-parachains/rococo/Cargo.toml
  polkadot-parachains/shell/Cargo.toml
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/westmint/Cargo.toml
  primitives/core/Cargo.toml
  primitives/parachain-inherent/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/utility/Cargo.toml
  test/client/Cargo.toml
  test/relay-sproof-builder/Cargo.toml
  test/relay-validation-worker-provider/Cargo.toml
  test/relay-validation-worker-provider/build.rs
  test/runtime/Cargo.toml
  test/service/Cargo.toml
Labels: A2-insubstantial, B1-releasenotes, M5-dependencies, C1-low 📌

#712 Moving `pallet-asset-tx-payment` from cumulus to substrate
  Cargo.lock
  Cargo.toml
  pallets/asset-tx-payment/Cargo.toml
  pallets/asset-tx-payment/README.md
  pallets/asset-tx-payment/src/lib.rs
  pallets/asset-tx-payment/src/payment.rs
  pallets/asset-tx-payment/src/tests.rs
  polkadot-parachains/parachains-common/Cargo.toml
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/westmint/Cargo.toml
Labels: A3-inprogress

#761 Add changelog generation
  .github/workflows/draft_release.yml
  scripts/changelog/.gitignore
  scripts/changelog/Gemfile
  scripts/changelog/Gemfile.lock
  scripts/changelog/README.md
  scripts/changelog/bin/changelog
  scripts/changelog/changelog.sh
  scripts/changelog/digests/.gitignore
  scripts/changelog/digests/.gitkeep
  scripts/changelog/lib/changelog.rb
  scripts/changelog/templates/change.md.tera
  scripts/changelog/templates/changes.md.tera
  scripts/changelog/templates/changes_client.md.tera
  scripts/changelog/templates/changes_misc.md.tera
  scripts/changelog/templates/changes_runtime.md.tera
  scripts/changelog/templates/compiler.md.tera
  scripts/changelog/templates/debug.md.tera
  scripts/changelog/templates/docker_image.md.tera
  scripts/changelog/templates/global_priority.md.tera
  scripts/changelog/templates/host_functions.md.tera
  scripts/changelog/templates/migrations.md.tera
  scripts/changelog/templates/pre_release.md.tera
  scripts/changelog/templates/priority.md.tera
  scripts/changelog/templates/runtime.md.tera
  scripts/changelog/templates/runtimes.md.tera
  scripts/changelog/templates/template.md.tera
  scripts/changelog/test/test_basic.rb
  scripts/github/runtime-version.rb
Labels: A2-insubstantial, A0-pleasereview, B0-silent

#765 Remove dead dep.
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌, A7-companion

#780 Add srtool check in master and release branches
  .github/workflows/srtool.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent

#781 Backport changelog to the release branch
  .github/workflows/draft_release.yml
  scripts/changelog/.gitignore
  scripts/changelog/Gemfile
  scripts/changelog/Gemfile.lock
  scripts/changelog/README.md
  scripts/changelog/bin/changelog
  scripts/changelog/changelog.sh
  scripts/changelog/digests/.gitignore
  scripts/changelog/digests/.gitkeep
  scripts/changelog/lib/changelog.rb
  scripts/changelog/templates/change.md.tera
  scripts/changelog/templates/changes.md.tera
  scripts/changelog/templates/changes_client.md.tera
  scripts/changelog/templates/changes_misc.md.tera
  scripts/changelog/templates/changes_runtime.md.tera
  scripts/changelog/templates/compiler.md.tera
  scripts/changelog/templates/debug.md.tera
  scripts/changelog/templates/docker_image.md.tera
  scripts/changelog/templates/global_priority.md.tera
  scripts/changelog/templates/host_functions.md.tera
  scripts/changelog/templates/migrations.md.tera
  scripts/changelog/templates/pre_release.md.tera
  scripts/changelog/templates/priority.md.tera
  scripts/changelog/templates/runtime.md.tera
  scripts/changelog/templates/runtimes.md.tera
  scripts/changelog/templates/template.md.tera
  scripts/changelog/test/test_basic.rb
  scripts/github/runtime-version.rb
Labels: A2-insubstantial, A0-pleasereview, B0-silent

#783 Fix CODEOWNERS syntax
  CODEOWNERS
Labels: A2-insubstantial, C1-low 📌

#786 Fix rococo naming (#785)
  .github/workflows/draft_release.yml
  scripts/changelog/bin/changelog
Labels: A2-insubstantial, A8-backport, C1-low 📌

#790 Add checks, debug and doc
  scripts/generate_genesis_value.sh
  scripts/scale_encode_genesis/index.js
Labels: A2-insubstantial, B0-silent, C1-low 📌

#791 Fix use of weight limit errors
  pallets/xcmp-queue/src/lib.rs
Labels: A0-pleasereview

#788 CI: Release start
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/release-01_rc-automation.yml
  .github/workflows/release-02_create-draft.yml
  .github/workflows/release-99_bot-announce.yml
  pallets/xcmp-queue/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#795 Backport Fix use of weight limit errors (#791)
  pallets/xcmp-queue/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, A8-backport, C1-low 📌

#798 Backport Fix use of weight limit errors (#791) for Polkadot 0.9.13
  pallets/xcmp-queue/src/lib.rs
Labels: B1-releasenotes, A8-backport, C1-low 📌
