Repository paritytech/cumulus, pull requests merged in 2021-10, with the labels that each got.

#642 Make asset creation on westmint low cost
  polkadot-parachains/westmint/src/lib.rs
Labels: A2-insubstantial, B1-releasenotes

#552 Statemint Reserve Asset Transfer
  Cargo.lock
  polkadot-parachains/parachains-common/Cargo.toml
  polkadot-parachains/parachains-common/src/impls.rs
  polkadot-parachains/parachains-common/src/lib.rs
  polkadot-parachains/rococo/Cargo.toml
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, M5-statemint

#517 Look at the upgrade go-ahead and restriction signals
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/migration.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/tests.rs
  primitives/parachain-inherent/src/client_side.rs
  test/relay-sproof-builder/src/lib.rs
Labels: A0-pleasereview

#656 add minimal mention of Statemint in the readme
  README.md
Labels: M5-statemint

#668 Add script to generate simple changelogs
  scripts/changelog/.gitignore
  scripts/changelog/README.md
  scripts/changelog/changelog.sh
Labels: A2-insubstantial, A0-pleasereview

#669 disable permissionless asset creation for Statemint
  polkadot-parachains/statemint/src/lib.rs
Labels: M5-statemint

#713 Udpate polkadot substrate
  Cargo.lock
  pallets/dmp-queue/src/lib.rs
Labels: Q0-trivial
