Repository paritytech/cumulus, pull requests merged in 2021-09, with the labels that each got.

#591 Add script and dockerfile to build an injected docker image for the polkadot-collator binary
  .dockerignore
  README.md
  docker/injected.Dockerfile
  docker/scripts/build-injected-image.sh
  docker/test-parachain-collator.dockerfile
  polkadot-parachains/res/statemint.json
Labels: A2-insubstantial, A0-pleasereview

#603 dockerfiles: upgrade to ubuntu:20.04
  docker/injected.Dockerfile
Labels: A0-pleasereview, F7-optimisation ⏱, M0-build

#564 Metadata v14 (companion to #3336)
  Cargo.lock
  client/cli/src/lib.rs
  pallets/aura-ext/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/collator-selection/src/lib.rs
  pallets/dmp-queue/Cargo.toml
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/xcm/Cargo.toml
  pallets/xcm/src/lib.rs
  pallets/xcmp-queue/Cargo.toml
  pallets/xcmp-queue/src/lib.rs
  polkadot-parachains/pallets/parachain-info/Cargo.toml
  polkadot-parachains/pallets/ping/Cargo.toml
  polkadot-parachains/pallets/ping/src/lib.rs
  polkadot-parachains/parachains-common/Cargo.toml
  polkadot-parachains/rococo/Cargo.toml
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/shell/Cargo.toml
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
  primitives/parachain-inherent/Cargo.toml
  primitives/parachain-inherent/src/lib.rs
  test/client/src/lib.rs
  test/runtime-upgrade/Cargo.toml
  test/runtime/Cargo.toml
  test/runtime/src/lib.rs
  test/service/src/lib.rs
Labels: A0-pleasereview

#618 bump deps
  Cargo.lock
  polkadot-parachains/statemine/src/weights/pallet_balances.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/pallet_balances.rs
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/pallet_balances.rs
Labels: A0-pleasereview

#623 chore: bump subwasm version to support V14 runtimes
  .github/workflows/srtool.yml
Labels: A2-insubstantial, A0-pleasereview

#629 Add extrincic ordering check to CI
  .github/workflows/extrinsic-ordering-check-from-bin.yml
  scripts/extrinsic-ordering-filter.sh
Labels: A2-insubstantial, M1-ci
