Repository paritytech/cumulus, pull requests merged in 2021-07, with the labels that each got.

#516 Propose bumping StringLimit to 128 bytes
  polkadot-parachains/rococo/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview

#526 upgrade srtool-actions and subwasm
  .github/workflows/srtool.yml
Labels: A0-pleasereview, M1-ci

#528 Update Polkadot and Substrate
  Cargo.lock
  pallets/parachain-system/src/lib.rs
Labels: A0-pleasereview

#537 Properly declare #[pallet::validate_unsigned] in ParachainSystem
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
Labels: A0-pleasereview, B0-patchthis

#476 Enable permissionless asset creation
  Cargo.lock
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
Labels: A2-insubstantial, M5-statemint

#493 Add Uniques to Westmint and Statemint
  Cargo.lock
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/mod.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/mod.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
Labels: M5-statemint

#527 CI: build a test artifact
  .gitlab-ci.yml
  scripts/ci/pre_cache.sh
Labels: A3-inprogress, B0-patchthis

#550 ci: upgrade subwasm
  .github/workflows/srtool.yml
Labels: A0-pleasereview, A2-insubstantial

#547 ci: reduce the list of events triggering matrix messages
  .github/workflows/release-bot.yml
Labels: A0-pleasereview, A2-insubstantial, M1-ci
