Repository paritytech/cumulus, pull requests merged in 2021-12, with the labels that each got.

#711 companion for pallet order fix
  Cargo.lock
  pallets/collator-selection/src/mock.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  test/runtime/src/lib.rs
Labels: A8-looksgood, A7-companion

#815 Format cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/session-benchmarking/Cargo.toml
  pallets/xcmp-queue/Cargo.toml
  parachain-template/runtime/Cargo.toml
  polkadot-parachains/Cargo.toml
  polkadot-parachains/parachains-common/Cargo.toml
  polkadot-parachains/rococo-parachain/Cargo.toml
  polkadot-parachains/shell/Cargo.toml
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/westmint/Cargo.toml
  test/relay-sproof-builder/Cargo.toml
Labels: B0-silent, Q0-trivial, C1-low 📌

#817 Add Statemint Genesis Values
  polkadot-parachains/res/statemint.json
  polkadot-parachains/res/statemint_genesis.json
  polkadot-parachains/res/statemint_genesis_values.json
  polkadot-parachains/res/statemint_genesis_values.scale
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/command.rs
  scripts/generate_genesis_value.sh
  scripts/generate_genesis_values/index.js
  scripts/scale_encode_genesis/index.js
Labels: A0-pleasereview, B0-silent, M5-statemint, C1-low 📌

#819 Add Release Automation Files to Allow for Manual Workflow Triggering
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/release-01_rc-automation.yml
  .github/workflows/release-02_create-draft.yml
  .github/workflows/release-99_bot-announce.yml
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#822 Backport: Fix secret used to send announcements
  .github/workflows/release-01_rc-automation.yml
  .github/workflows/release-02_create-draft.yml
Labels: A8-backport

#813 Refactor some types in XCMP queue
  pallets/xcmp-queue/src/lib.rs
Labels: A0-pleasereview, C1-low 📌

#793 Integrate try-runtime into cumulus
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  client/cli/src/lib.rs
  pallets/collator-selection/Cargo.toml
  pallets/collator-selection/src/benchmarking.rs
  pallets/session-benchmarking/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  parachain-template/pallets/template/Cargo.toml
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/shell/Cargo.toml
  polkadot-parachains/src/cli.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C3-medium 📣

#782 Add check_labels script and workflow
  .github/workflows/check-labels.yml
  scripts/common/lib.sh
  scripts/github/check_labels.sh
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#836 Add CI to build docker images on releases
  .github/workflows/release-10_docker.yml
  .github/workflows/release-99_bot-announce.yml
  docker/injected.Dockerfile
  docker/scripts/build-injected-image.sh
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#829 Fix Statemine ss58 prefixes.
  polkadot-parachains/res/statemine.json
  polkadot-parachains/res/statemine_genesis.json
  polkadot-parachains/src/chain_spec.rs
Labels: B0-silent, C1-low 📌

#824 Seedling Runtime + Node
  Cargo.lock
  polkadot-parachains/Cargo.toml
  polkadot-parachains/seedling/Cargo.toml
  polkadot-parachains/seedling/build.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/service.rs
  scripts/create_seedling_spec.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#799 Support overweight messages in XCMP queue
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/migration.rs
  pallets/xcmp-queue/src/mock.rs
  pallets/xcmp-queue/src/tests.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#847 Add CheckNonZeroSender to runtime configs
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  test/client/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#804 Companion for #10382 (Insufficient asset quotes and deposits)
  Cargo.lock
  pallets/collator-selection/src/mock.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/pallets/template/src/mock.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/parachains-common/src/impls.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  test/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌

#850 Update to latest Polkadot & Substrate
  Cargo.lock
  client/cli/src/lib.rs
  pallets/xcmp-queue/src/tests.rs
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/service.rs
  test/client/src/lib.rs
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#852 Update again
  Cargo.lock
  client/network/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#849 Update Substrate & Polkadot
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#854 Fix benchmarks and ensure CI tests them
  .gitlab-ci.yml
  test/service/benches/transaction_throughput.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#858 Test-runtime: Support changing the `ParaId`.
  test/service/src/chain_spec.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#855 Bump Polkadot and fix
  Cargo.lock
  parachain-template/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#842 Companion for #10403: Remove Default for AccountId
  Cargo.lock
  pallets/collator-selection/src/mock.rs
  pallets/session-benchmarking/Cargo.toml
  pallets/session-benchmarking/src/lib.rs
  polkadot-parachains/parachains-common/src/impls.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  test/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#861 Update Substrate & Polkadot
  Cargo.lock
  test/client/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#838 Disable asset transfers on Statemint (against master branch)
  polkadot-parachains/statemint/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#856 Companion for #10440 (Add logger configuration hook)
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#864 Substrate companion for fetching slot duration
  Cargo.lock
  client/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#871 Update serde to 1.0.132
  pallets/aura-ext/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/parachain-system/Cargo.toml
  pallets/xcm/Cargo.toml
  parachain-template/node/Cargo.toml
  parachain-template/pallets/template/Cargo.toml
  parachain-template/runtime/Cargo.toml
  polkadot-parachains/Cargo.toml
  polkadot-parachains/pallets/parachain-info/Cargo.toml
  polkadot-parachains/pallets/ping/Cargo.toml
  polkadot-parachains/rococo-parachain/Cargo.toml
  polkadot-parachains/seedling/Cargo.toml
  polkadot-parachains/shell/Cargo.toml
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/westmint/Cargo.toml
  test/runtime/Cargo.toml
  test/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#873 companion for polkadot#4542
  Cargo.lock
  client/network/src/tests.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#835 Introduce interface for relay chain interaction
  Cargo.lock
  Cargo.toml
  client/collator/Cargo.toml
  client/collator/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/lib.rs
  client/consensus/common/Cargo.toml
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/relay-chain/Cargo.toml
  client/consensus/relay-chain/src/lib.rs
  client/network/Cargo.toml
  client/network/src/lib.rs
  client/network/src/tests.rs
  client/network/src/wait_on_relay_chain_block.rs
  client/pov-recovery/Cargo.toml
  client/pov-recovery/src/lib.rs
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-local/Cargo.toml
  client/relay-chain-local/src/lib.rs
  client/service/Cargo.toml
  client/service/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/service.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/src/service.rs
  primitives/parachain-inherent/Cargo.toml
  primitives/parachain-inherent/src/client_side.rs
  test/service/Cargo.toml
  test/service/src/lib.rs
Labels: B0-silent

#678 Companion for substrate#9732
  Cargo.lock
  client/collator/src/lib.rs
  client/service/src/genesis.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  parachain-template/node/src/command.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  test/relay-sproof-builder/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/genesis.rs
Labels: B7-runtimenoteworthy, C1-low 📌, A7-companion

#876 Mock XCM
  Cargo.lock
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  primitives/parachain-inherent/Cargo.toml
  primitives/parachain-inherent/src/lib.rs
  primitives/parachain-inherent/src/mock.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#875 companion for polkadot#4545 (session-info v2)
  Cargo.lock
  client/relay-chain-local/src/lib.rs
  primitives/core/src/lib.rs
Labels: B0-silent, C1-low 📌, A7-companion

#877 update polkadot
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#879 Update proc-macro2 to 1.0.36
  Cargo.lock
  pallets/parachain-system/proc-macro/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#880 companion for polkadot#4635 (config rename frequency->cooldown)
  Cargo.lock
  test/relay-sproof-builder/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#878 minor dmq test
  pallets/parachain-system/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌
