Repository paritytech/cumulus, pull requests merged in 2022-06, with the labels that each got.

#1300 Fixup benches after dir re-org
  .gitlab-ci.yml
  scripts/benchmarks-ci.sh
  scripts/benchmarks.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1318 Statemint Should Not Recognise DOT Reserves
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌

#1311 Publish polkadot-parachain docker images on PRs
  .gitlab-ci.yml
  docker/polkadot-parachain-debug_unsigned_injected.Dockerfile
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1326 Run the release branch check on the cumulus code releases as well
  .github/workflows/release-01_branch-check.yml
  scripts/ci/github/check-rel-br
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1327 [ci] Add build docker test-parachain for zombienet
  .gitlab-ci.yml
  docker/test-parachain_injected.Dockerfile
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1280 Ensure relay chain block number strictly increases
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌

#1331 chore: rm unused sc-service
  Cargo.lock
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-interface/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1297 Add client checklist + doc
  .github/ISSUE_TEMPLATE/release-client.md
  .github/ISSUE_TEMPLATE/release-runtime.md
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/release-01_rc-automation.yml
  docs/release.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1341 Update substrate after #11593
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1340 Upgrade spec_version to `9230` and bump `transaction_version` for assets parachains.
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌, R0-CGP

#1348 Backport of 1318
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: A8-backport, B7-runtimenoteworthy, C1-low 📌

#1344 Validation-worker: Add support for patches and rerun on Cargo.lock
  Cargo.lock
  test/relay-validation-worker-provider/Cargo.toml
  test/relay-validation-worker-provider/build.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1351 Fix client workflow (#1292 backport to release branch)
  .github/workflows/release-02_create-draft.yml
Labels: A8-backport, B0-silent, C1-low 📌

#1353 Backport of 1318 to collator release branch (#1348)
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: A8-backport, B0-silent, C1-low 📌

#1360 Derive MaxEncodedLen on cumulus_pallet_xcm::Origin
  pallets/xcm/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1359 Bounded aura ext pallet
  Cargo.lock
  pallets/aura-ext/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1362 Backport to runtime release branch of Fix `release-parachains-v*` pipelines (#1355)
  .gitlab-ci.yml
Labels: A8-backport, B0-silent, C1-low 📌

#1337 Bounded collator selection pallet
  pallets/collator-selection/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1332 Lower all Assets / NFT deposits by 10x
  parachains/runtimes/assets/statemine/src/constants.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/constants.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/constants.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/constants.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌

#1369 Backport #1332
  parachains/runtimes/assets/statemine/src/constants.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/constants.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/constants.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/constants.rs
Labels: A8-backport, B7-runtimenoteworthy, C1-low 📌

#1373 Updated weights
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1333 Bounded ping pallet
  parachains/pallets/ping/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1367 Companion for substrate#11618
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, C1-low 📌

#1363 Companion for paritytech/substrate#11631
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1379 Add upstream new args
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1382 Disable beefy for inprocess relay chain node
  client/relay-chain-inprocess-interface/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1347 Split chain_spec to individual chain families
  polkadot-parachain/src/chain_spec/contracts.rs
  polkadot-parachain/src/chain_spec/mod.rs
  polkadot-parachain/src/chain_spec/seedling.rs
  polkadot-parachain/src/chain_spec/shell.rs
  polkadot-parachain/src/chain_spec/statemint.rs
  polkadot-parachain/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1303 Remove redundant binary specification
  parachain-template/node/Cargo.toml
  parachain-template/polkadot-launch/config.json
  polkadot-parachain/Cargo.toml
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#1325 Move `ExportGenesisStateCommand` and `ExportGenesisWasmCommand` to cumulus-client-cli
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/service/Cargo.toml
  client/service/src/genesis.rs
  client/service/src/lib.rs
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/cli.rs
  polkadot-parachain/src/command.rs
  test/service/Cargo.toml
  test/service/src/cli.rs
  test/service/src/genesis.rs
  test/service/src/main.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1385 NonTransfer should be a superset of collator selection
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1386 Remove futures compat feature
  Cargo.lock
  client/collator/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/common/Cargo.toml
  client/consensus/relay-chain/Cargo.toml
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  polkadot-parachain/Cargo.toml
  primitives/timestamp/Cargo.toml
  test/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1286 Add event with XCM executor outcome, which includes weight fee
  pallets/xcmp-queue/src/lib.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌

#1391 Fix patch handling for `relay-validation-worker-provider` build script
  test/relay-validation-worker-provider/build.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1397 Collectives polkadot runtime to cargo workspace members
  Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1398 Polkadot collectives: use unit type impl for identity verifier
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1389 rename build_import_queue to not be statemint specific
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1392 Rename help string `parachain-collator` -> `parachain-template-node`
  parachain-template/node/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1405 Disable beefy for inprocess relay chain node (#1382)
  client/relay-chain-inprocess-interface/src/lib.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#1402 rename now shared node creation function
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1404 Companion for substrate#11501
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌, A7-companion

#1403 README: installation instructions
  README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1401 Remove left over runtime sections for client builds
  scripts/ci/changelog/templates/changes.md.tera
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1411 Fix GHA hash
  .github/workflows/release-01_rc-automation.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1378 add wss bootnodes to statemine/t chainspec
  parachains/chain-specs/statemine.json
  parachains/chain-specs/statemint.json
Labels: A0-pleasereview, B0-silent, F8-enhancement 🎁, P5-sometimesoon, Q0-trivial, R1-statemint, C1-low 📌

#1418 Fix Docker CI
  .github/workflows/release-10_docker-manual.yml
  .github/workflows/release-10_docker.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1420 Second part of the Docker CI fix
  .github/workflows/release-10_docker-manual.yml
  .github/workflows/release-10_docker.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌
