Repository paritytech/cumulus, pull requests merged in 2022-04, with the labels that each got.

#1130 Bump version to v900
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1137 Bump `lru` to 0.7.4
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1133 Bump tx version due to substrate 10896
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#1131 Bump collator version to 5.4
  Cargo.lock
  polkadot-parachains/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1152 Add LengthToFee to runtimes
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1142 create .github/pr-custom-review.yml
  .github/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1155 fix pr-custom-review.yml
  .github/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1154 Remove old caching stuff from CI
  .gitlab-ci.yml
  scripts/ci/pre_cache.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1156 Co #11164: Sub-commands for `benchmark`
  Cargo.lock
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  polkadot-parachains/src/cli.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/tests/benchmark_storage_works.rs
Labels: A0-pleasereview, B1-releasenotes, B2-breaksapi, C1-low 📌, B5-client

#1153 Create .github/workflows/pr-custom-review.yml
  .github/workflows/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1135 Make functionality to read relay state proof entries public
  pallets/parachain-system/src/relay_state_snapshot.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1074 Add benchmarks to pipeline
  .gitlab-ci.yml
  scripts/benchmarks-ci.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1167 Fix rules for benchmarks and publish
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1168 CI: rename ambiguous jobs
  .github/workflows/pr-custom-review.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1108 Handle relocation of `ParachainHost` in Polkadot
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
  primitives/core/src/lib.rs
Labels: B0-silent, C1-low 📌

#1147 Log XCMP Queue Errors
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1161 use the right MMR primitives crate (companion for substrate#11183)
  Cargo.lock
Labels: B0-silent, C1-low 📌, A7-companion

#1173 Update Substrate & Polkadot
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1172 Co #11198: Expose `benchmark machine` command
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#1180 Update Substrate & Polkadot
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1169 Deny using relay chain for reserve transfers
  parachain-template/runtime/src/xcm_config.rs
  polkadot-parachains/canvas-kusama/src/xcm_config.rs
  polkadot-parachains/parachains-common/src/lib.rs
  polkadot-parachains/parachains-common/src/xcm_config.rs
  polkadot-parachains/statemine/src/xcm_config.rs
  polkadot-parachains/statemint/src/xcm_config.rs
  polkadot-parachains/westmint/src/xcm_config.rs
Labels: A0-pleasereview, B1-releasenotes, M5-statemint, B7-runtimenoteworthy, C1-low 📌, T6-XCM

#1186 Aura: Switch to `SimpleSlotWorker`
  Cargo.lock
  client/consensus/aura/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1187 Implement set_block_number for runtime-bencmarks in RelayBlockNumberP…
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1190 warn not info
  polkadot-parachains/parachains-common/src/xcm_config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1188 Skip pr-custom-review if pull request is in Draft
  .github/workflows/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1203 Fix priority thresholds
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1204 Fix release notes prio backport (#1203)
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1193 Updated weights for v900 release
  polkadot-parachains/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/statemine/src/weights/frame_system.rs
  polkadot-parachains/statemine/src/weights/pallet_assets.rs
  polkadot-parachains/statemine/src/weights/pallet_balances.rs
  polkadot-parachains/statemine/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemine/src/weights/pallet_multisig.rs
  polkadot-parachains/statemine/src/weights/pallet_proxy.rs
  polkadot-parachains/statemine/src/weights/pallet_session.rs
  polkadot-parachains/statemine/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemine/src/weights/pallet_utility.rs
  polkadot-parachains/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/statemint/src/weights/frame_system.rs
  polkadot-parachains/statemint/src/weights/pallet_assets.rs
  polkadot-parachains/statemint/src/weights/pallet_balances.rs
  polkadot-parachains/statemint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemint/src/weights/pallet_multisig.rs
  polkadot-parachains/statemint/src/weights/pallet_proxy.rs
  polkadot-parachains/statemint/src/weights/pallet_session.rs
  polkadot-parachains/statemint/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/weights/pallet_utility.rs
  polkadot-parachains/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/westmint/src/weights/frame_system.rs
  polkadot-parachains/westmint/src/weights/pallet_assets.rs
  polkadot-parachains/westmint/src/weights/pallet_balances.rs
  polkadot-parachains/westmint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/westmint/src/weights/pallet_multisig.rs
  polkadot-parachains/westmint/src/weights/pallet_proxy.rs
  polkadot-parachains/westmint/src/weights/pallet_session.rs
  polkadot-parachains/westmint/src/weights/pallet_timestamp.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1207 Default not implemented for non-std builds for PersistedValidationData
  pallets/parachain-system/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1191 benchmark now takes a command
  scripts/benchmarks-ci.sh
  scripts/benchmarks.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1211 Fix priority thresholds (#1203)
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1212 warn not info (#1190)
  polkadot-parachains/parachains-common/src/xcm_config.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1210 bash tutorial: change the working path after clone
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1216 [ci] Fix benchmark branch name and typo
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1113 Companion for Substrate#11062
  Cargo.lock
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/src/cli.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A7-companion

#1214 Co #11270: Update benchmark machine command
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1085 Companion for #11025 (Uniques Locker Trait)
  Cargo.lock
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1221 Companion for substrate#11009
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌, A7-companion
