Repository paritytech/cumulus, pull requests merged in 2022-01, with the labels that each got.

#883 Update Polkadot
  Cargo.lock
Labels: A0-pleasereview, B0-silent, C1-low 📌

#882 Fix solo to para custom header return
  client/collator/src/lib.rs
  pallets/parachain-system/src/lib.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  primitives/core/src/lib.rs
  test/runtime/src/lib.rs
  test/service/tests/full_node_catching_up.rs
  test/service/tests/migrate_solo_to_para.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#884 Derive Clone for RelayStateSproofBuilder
  test/relay-sproof-builder/src/lib.rs
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#886 Fix transaction benchmark
  test/service/benches/transaction_throughput.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#870 Cumulus companion for substrate #10463
  Cargo.lock
  parachain-template/node/src/chain_spec.rs
  polkadot-parachains/src/chain_spec.rs
  test/service/src/chain_spec.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#890 Companion for #4639 (Remove sleep from tests )
  Cargo.lock
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#894 Companion for substrate#10620
  Cargo.lock
  pallets/parachain-system/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#897 Remove Sudo from Westmint
  Cargo.lock
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, M5-statemint, C1-low 📌

#868 Use Polkadot Constants instead of Hardcoding
  Cargo.lock
  client/cli/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/constants.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/constants.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/constants.rs
Labels: A0-pleasereview, B0-silent, M5-statemint, C1-low 📌

#846 Add set custom header to Seedling Runtime
  Cargo.lock
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/solo-to-para/Cargo.toml
  pallets/solo-to-para/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/Cargo.toml
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  primitives/core/Cargo.toml
  primitives/core/src/lib.rs
  scripts/create_seedling_spec.sh
  test/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#907 companion for polkadot/4078
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#899 Fix broken links in README
  README.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#903 bump transaction_version due to parachain_system change (#748)
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#912 Configure Statemint and Statemine to Allow Teleports
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#905 Add Statemint Genesis Values (#817)
  polkadot-parachains/res/statemint.json
  polkadot-parachains/res/statemint_genesis.json
  polkadot-parachains/res/statemint_genesis_values.json
  polkadot-parachains/res/statemint_genesis_values.scale
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/command.rs
  scripts/generate_genesis_value.sh
  scripts/generate_genesis_values/index.js
  scripts/scale_encode_genesis/index.js
Labels: A0-pleasereview, B0-silent, C1-low 📌

#915 merge back: weights update statemine v6 (#754)
  polkadot-parachains/statemine/src/weights/pallet_assets.rs
  polkadot-parachains/statemine/src/weights/pallet_balances.rs
  polkadot-parachains/statemine/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemine/src/weights/pallet_multisig.rs
  polkadot-parachains/statemine/src/weights/pallet_proxy.rs
  polkadot-parachains/statemine/src/weights/pallet_session.rs
  polkadot-parachains/statemine/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemine/src/weights/pallet_utility.rs
  polkadot-parachains/statemint/src/weights/pallet_assets.rs
  polkadot-parachains/statemint/src/weights/pallet_balances.rs
  polkadot-parachains/statemint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemint/src/weights/pallet_multisig.rs
  polkadot-parachains/statemint/src/weights/pallet_proxy.rs
  polkadot-parachains/statemint/src/weights/pallet_session.rs
  polkadot-parachains/statemint/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/weights/pallet_utility.rs
  polkadot-parachains/westmint/src/weights/pallet_assets.rs
  polkadot-parachains/westmint/src/weights/pallet_balances.rs
  polkadot-parachains/westmint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/westmint/src/weights/pallet_multisig.rs
  polkadot-parachains/westmint/src/weights/pallet_proxy.rs
  polkadot-parachains/westmint/src/weights/pallet_session.rs
  polkadot-parachains/westmint/src/weights/pallet_timestamp.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#889 xcmp-queue: Fix handling of encoded blobs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#900 Add collator selection tool tips
  pallets/collator-selection/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#911 Add the uniques migration for statemine
  Cargo.lock
  polkadot-parachains/statemine/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#898 Pin the changelogerator version
  .github/workflows/release-02_create-draft.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#917 co #4746: Require `MaxEncodedLen` per default
  Cargo.lock
  pallets/aura-ext/src/lib.rs
  pallets/collator-selection/src/lib.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/solo-to-para/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  polkadot-parachains/pallets/ping/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A7-companion

#918 merge of: Add system weights to Statemint (#762)
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/weights/frame_system.rs
  polkadot-parachains/statemine/src/weights/mod.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/frame_system.rs
  polkadot-parachains/statemint/src/weights/mod.rs
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/frame_system.rs
  polkadot-parachains/westmint/src/weights/mod.rs
  scripts/benchmarks.sh
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#923 Statemint: Support running statemint only with ed25519
  polkadot-parachains/parachains-common/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/service.rs
  polkadot-parachains/statemint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#901 Companion for paritytech/polkadot#4712
  Cargo.lock
  pallets/xcmp-queue/src/mock.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#919 merge of Bump the collator version
  Cargo.lock
  polkadot-parachains/Cargo.toml
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#926 Use `define_benchmarks!`
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, F6-refactor 🧹, C1-low 📌

#927 pov-recovery: Enable pov-recovery as well on full nodes
  client/pov-recovery/src/lib.rs
  client/pov-recovery/tests/pov_recovery.rs
  client/service/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/src/service.rs
  test/service/Cargo.toml
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#930 Update Substrate & Polkadot
  .gitlab-ci.yml
  Cargo.lock
  polkadot-parachains/parachains-common/src/impls.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#895 Companion for substrate#10632
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/src/cli.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#933 fix: remove duplicate event of pallet_balances
  polkadot-parachains/parachains-common/src/impls.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#934 Add production profile
  Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#909 Unify RelayChainInterface error handling and introduce async
  Cargo.lock
  client/consensus/common/Cargo.toml
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/common/src/tests.rs
  client/consensus/relay-chain/src/lib.rs
  client/network/src/lib.rs
  client/network/src/tests.rs
  client/pov-recovery/src/lib.rs
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-local/src/lib.rs
  client/service/src/lib.rs
  pallets/parachain-system/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/src/service.rs
  primitives/parachain-inherent/src/client_side.rs
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#904 Add safe_xcm_version to Genesis Specs (#743)
  Cargo.lock
  parachain-template/node/Cargo.toml
  parachain-template/node/src/chain_spec.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/rococo-parachain/Cargo.toml
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#896 Add the ability to suspend or resume XCM execution on the XCMP queue
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  pallets/xcmp-queue/src/tests.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  primitives/core/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌
