Repository paritytech/cumulus, pull requests merged in 2022-08, with the labels that each got.

#1462 Introduce RPC Worker
  Cargo.lock
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-rpc-interface/Cargo.toml
  client/relay-chain-rpc-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1491 Fix typos in release.md
  docs/release.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1488 gitignore dot-underscore
  .gitignore
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1431 Add script to run integration tests
  scripts/parachains_integration_tests.sh
Labels: A0-pleasereview, B0-silent, R1-statemint, C1-low 📌, R0-CGP

#1487 Companion for #11939
  Cargo.lock
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-rpc-interface/Cargo.toml
  parachain-template/node/Cargo.toml
  polkadot-parachain/Cargo.toml
  test/service/Cargo.toml
Labels: B0-silent, C1-low 📌, A7-companion

#1278 Statemint runtimes to accept sufficient assets as xcm fee payment
  Cargo.lock
  parachains/common/Cargo.toml
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemine/tests/tests.rs
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/statemint/tests/tests.rs
  parachains/runtimes/assets/test-utils/Cargo.toml
  parachains/runtimes/assets/test-utils/src/lib.rs
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/tests/tests.rs
  primitives/utility/Cargo.toml
  primitives/utility/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, R1-statemint, B7-runtimenoteworthy, C1-low 📌

#1473 slurp collectives digest to make appear in release notes
  scripts/ci/changelog/bin/changelog
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1504 Integrate auto-updating parachain template on developer-hub (#1479)
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1506 Fix templates
  .github/ISSUE_TEMPLATE/release-client.md
  .github/ISSUE_TEMPLATE/release-runtime.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1508 Same than https://github.com/paritytech/polkadot/pull/5751
  .github/workflows/release-01_branch-check.yml
  scripts/ci/github/check-rel-br
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1514 Renaming CLI prunning and keep-blocks flags
  Cargo.lock
  test/service/src/lib.rs
Labels: B2-breaksapi, B0-silent, C1-low 📌

#1494 Upgrade spec_version to `9230` and bump `transaction_version`
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: A0-pleasereview, B0-silent, R1-statemint, C1-low 📌

#1518 [Fix] Benchmark build artifact folder creation
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1519 [Fix] Benches in release branch
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1517 Align versions for starters runtimes
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: B0-silent, C1-low 📌

#1521 [benchmarks] Update weights
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1486 Trivial networking changes for Substrate PR #11940
  Cargo.lock
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/service.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/service.rs
  test/service/Cargo.toml
  test/service/src/lib.rs
Labels: B0-silent, C1-low 📌

#1526 Update Integration tests Statemine & Statemint
  parachains/integration-tests/statemine/xcm/0_init.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/xcm/0_init.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1522 [benchmarks] pr with weights master
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1536 Updated Proxy filter - removed calls from AssetOwner
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: B0-silent, C1-low 📌, A0-please_review, C1-low

#1537 Updated Proxy filter - removed calls from AssetOwner (#1536)
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, C1-low

#1534 [Fix] flaky node tests
  Cargo.lock
  polkadot-parachain/Cargo.toml
  polkadot-parachain/tests/common.rs
  polkadot-parachain/tests/polkadot_argument_parsing.rs
  polkadot-parachain/tests/polkadot_mdns_issue.rs
  polkadot-parachain/tests/purge_chain_works.rs
  polkadot-parachain/tests/running_the_node_and_interrupt.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, C1-low

#1516 [Fix] Some info in the release checklist
  .github/ISSUE_TEMPLATE/release-runtime.md
  docs/release.md
Labels: A0-pleasereview, B0-silent, C1-low 📌, documentation

#1510 CI fixes
  .github/ISSUE_TEMPLATE/release-client.md
  .github/ISSUE_TEMPLATE/release-runtime.md
  .github/workflows/release-01_branch-check.yml
  scripts/ci/github/check-rel-br
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1532 [ci] improve cancel-pipeline job
  .gitlab-ci.yml
Labels: B0-silent, A3-in_progress, C1-low

#1525 add tag creation for the runtimes release candidate
  .github/workflows/release-10_rc-automation.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, ci, enhancement

#1503 [ci] fix pipeline for polkadot-v branches
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#1346 Add Collectives Parachain
  .github/workflows/release-30_create-draft.yml
  .github/workflows/srtool.yml
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  parachains/chain-specs/collectives-polkadot.json
  parachains/chain-specs/collectives-westend.json
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/build.rs
  parachains/runtimes/collectives/collectives-polkadot/src/constants.rs
  parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/block_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/extrinsic_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/mod.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/paritydb_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/rocksdb_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/chain_spec/collectives.rs
  polkadot-parachain/src/chain_spec/mod.rs
  polkadot-parachain/src/chain_spec/statemint.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
  scripts/benchmarks-ci.sh
  scripts/benchmarks.sh
  scripts/ci/changelog/bin/changelog
Labels: A0-pleasereview, B7-runtimenoteworthy, C3-medium 📣

#1542 Backport core version fix
  scripts/ci/changelog/templates/runtime.md.tera
Labels: B0-silent, F9-release 🏷, C1-low 📌, A0-please_review, C1-low

#1548 Renaming to align with Polkadot
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
  .github/workflows/release-21_extrinsic-ordering-check-from-two.yml
  .github/workflows/release-30_create-draft.yml
  .github/workflows/release-50_docker-manual.yml
  .github/workflows/release-50_docker.yml
Labels: B0-silent, ci, A0-please_review, A6-backport, C1-low

#1500 Removed dependance on `rococo_parachain_runtime` for unrelated stuff
  Cargo.lock
  parachain-template/node/src/chain_spec.rs
  parachains/runtimes/starters/seedling/Cargo.toml
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/Cargo.toml
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/chain_spec/collectives.rs
  polkadot-parachain/src/chain_spec/contracts.rs
  polkadot-parachain/src/chain_spec/mod.rs
  polkadot-parachain/src/chain_spec/penpal.rs
  polkadot-parachain/src/chain_spec/rococo_parachain.rs
  polkadot-parachain/src/chain_spec/seedling.rs
  polkadot-parachain/src/chain_spec/statemint.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
Labels: B0-silent, A0-please_review, C1-low

#1533 [ci] change labels
  .github/dependabot.yml
  scripts/ci/github/check_labels.sh
Labels: B0-silent, A0-please_review, C1-low

#1535 Transaction payment runtime apis: query call info and fee details
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, X2-API

#1547 Removes duplication and unneeded sections of runtime release notes
  scripts/ci/changelog/templates/changes.md.tera
  scripts/ci/changelog/templates/template.md.tera
Labels: B0-silent, A0-please_review, C1-low

#1321 Zombienet add tests
  .gitlab-ci.yml
  test/service/src/cli.rs
  test/service/src/lib.rs
  test/service/src/main.rs
  zombienet_tests/0001-sync_blocks_from_tip_without_connected_collator.feature
  zombienet_tests/0001-sync_blocks_from_tip_without_connected_collator.toml
  zombienet_tests/0002-pov_recovery.feature
  zombienet_tests/0002-pov_recovery.toml
  zombienet_tests/0003-full_node_catching_up.feature
  zombienet_tests/0003-full_node_catching_up.toml
  zombienet_tests/0004-runtime_upgrade.feature
  zombienet_tests/0004-runtime_upgrade.toml
  zombienet_tests/0005-migrate_solo_to_para.feature
  zombienet_tests/0005-migrate_solo_to_para.toml
  zombienet_tests/migrate_solo_to_para.js
  zombienet_tests/runtime_upgrade.js
Labels: B0-silent, A0-please_review, C1-low, I5-tests

#1361 Companion for new trie cache
  Cargo.lock
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  test/relay-sproof-builder/src/lib.rs
  test/service/src/cli.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1556 Add new blank issue template
  .github/ISSUE_TEMPLATE/blank.md
Labels: B0-silent, A0-please_review, C1-low

#1557 Co #12059: Revert "Auto-incremental CollectionId"
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1553 [ci] Weights PR for master and client on cumulus
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#1560 chore: bump zombienet version
  .gitlab-ci.yml
Labels: B0-silent, ci, A0-please_review, C1-low

#1566 Pin GHA versions
  .github/workflows/docs.yml
  .github/workflows/release-30_create-draft.yml
Labels: A2-insubstantial, B0-silent, ci, C1-low, D3-trivial 🧸

#1567 shell and seedling did not build
  parachains/runtimes/starters/seedling/Cargo.toml
  parachains/runtimes/starters/shell/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low

#1562 [ci] add auto cargo-fmt
  .github/workflows/quick-check.yml
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#1573 Collectives runtime: alliance pallet upgrade introducing new retirement notice feature
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1579 [Feature] Limit collectives teleports to DOT
  parachains/common/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: T6-XCM, A0-please_review, B1-note_worthy, C1-low, X1-runtime
