Repository paritytech/cumulus, pull requests merged in 2022-07, with the labels that each got.

#1417 [ci] Send bench results to S3
  .gitlab-ci.yml
  scripts/benchmarks-ci.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1407 Less code in magic macros
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1426 Adding integration tests
  .gitignore
  parachains/integration-tests/statemine/config.toml
  parachains/integration-tests/statemine/xcm/0_init.yml
  parachains/integration-tests/statemine/xcm/1_dmp.yml
  parachains/integration-tests/statemine/xcm/2_ump.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/config.toml
  parachains/integration-tests/statemint/xcm/0_init.yml
  parachains/integration-tests/statemint/xcm/1_dmp.yml
  parachains/integration-tests/statemint/xcm/2_ump.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: A0-pleasereview, B0-silent, R1-statemint, C1-low 📌

#1430 standard way to get at the docs
  README.md
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1429 Update Readme for integration-tests
  parachains/README.md
Labels: A0-pleasereview, B0-silent, R1-statemint, C1-low 📌, R0-CGP

#1432 Add new room to the matrix notifications
  .github/workflows/release-99_bot-announce.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1437 Typo + some clippy stuff (unnecessary clone/to_string/refs)
  client/cli/src/lib.rs
  client/pov-recovery/src/lib.rs
  client/service/src/lib.rs
  pallets/parachain-system/src/lib.rs
  parachain-template/node/src/rpc.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/rpc.rs
  polkadot-parachain/src/service.rs
  test/client/src/block_builder.rs
  test/client/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/cli.rs
  test/service/src/lib.rs
  test/service/src/main.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1438 Weights updated for alliance-bench PR for alliance PR
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1427 Bench alliance
  .gitlab-ci.yml
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
  polkadot-parachain/src/command.rs
  scripts/benchmarks-ci.sh
  scripts/benchmarks.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1436 Companion for substrate#11786
  Cargo.lock
  client/cli/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  test/service/src/cli.rs
Labels: B1-releasenotes, C1-low 📌, B5-client

#1324 Companion to #11398
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, A7-companion

#1410 Use genesis_state_version param instead of StateVersion::V0
  client/cli/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1441 chainspecs for collectives-westend
  .github/workflows/release-02_create-draft.yml
  .github/workflows/srtool.yml
  parachains/chain-specs/collectives-polkadot.json
  parachains/chain-specs/collectives-westend.json
  polkadot-parachain/src/command.rs
Labels: A3-inprogress, B0-silent, C1-low 📌

#1350 Co #11456: Match statement fallthrough for `benchmark` commands
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1447 Companion for polkadot#5782
  Cargo.lock
  client/collator/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1456 Cleanup light client leftovers
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
  docs/overview.md
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: A8-looksgood, B0-silent, C1-low 📌, A7-companion

#1442 companion for https://github.com/paritytech/polkadot/pull/5770
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, A7-companion

#1475 [ci] Add timeout to benchmark job
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1477 [ci] use nextest for tests
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1419 Add epoch index to RelayStateSproofBuilder (for testing)
  test/relay-sproof-builder/src/lib.rs
Labels: A0-pleasereview, B0-silent, Q0-trivial, C1-low 📌

#1390 Companion for substrate#11523
  Cargo.lock
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/validate_block/implementation.rs
  test/runtime/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A7-companion

#1479 Integrate auto-updating parachain template on developer-hub
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1483 Adding TxVersion Check to signed params
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1377 Companion for substrate#11690
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1460 companion for #11796
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌
