Repository paritytech/cumulus, pull requests merged in 2022-11, with the labels that each got.

#1424 Add trie migration rpc to polkadot-parachain
  Cargo.lock
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/rpc.rs
  polkadot-parachain/src/service.rs
Labels: B0-silent, A0-please_review, C1-low

#1716 rename polkadot-parachain package to avoid name clash
  Cargo.lock
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1820 update substrate and polkadot deps
  Cargo.lock
Labels: B0-silent, T10-release, A0-please_review, C1-low, D3-trivial 🧸

#1824 Cargo.lock updated
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1817 Use resolver 2 in the workspace.
  Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low

#1818 BlockId removal: &Hash to Hash
  Cargo.lock
  client/consensus/common/src/parachain_consensus.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  primitives/parachain-inherent/src/mock.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1832 [Backport] #1805 Update `pallet-multisig` benches to node release branch
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, T0-node

#1833 [Backport] #1805 Update `pallet-multisig` benches to runtimes release branch
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, T1-runtime

#1813 Collectives: alliance and collective pallets weights
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/mod.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1839 Add example zombienet network file and instructions
  README.md
  scripts/ci/gitlab/pipeline/zombienet.yml
  zombienet/examples/small_network.toml
  zombienet/tests/0001-sync_blocks_from_tip_without_connected_collator.feature
  zombienet/tests/0001-sync_blocks_from_tip_without_connected_collator.toml
  zombienet/tests/0002-pov_recovery.feature
  zombienet/tests/0002-pov_recovery.toml
  zombienet/tests/0003-full_node_catching_up.feature
  zombienet/tests/0003-full_node_catching_up.toml
  zombienet/tests/0004-runtime_upgrade.feature
  zombienet/tests/0004-runtime_upgrade.toml
  zombienet/tests/0005-migrate_solo_to_para.feature
  zombienet/tests/0005-migrate_solo_to_para.toml
  zombienet/tests/0006-rpc_collator_builds_blocks.feature
  zombienet/tests/0006-rpc_collator_builds_blocks.toml
  zombienet/tests/migrate_solo_to_para.js
  zombienet/tests/register-para.js
  zombienet/tests/runtime_upgrade.js
Labels: B0-silent, A0-please_review, C1-low

#1837 fix failing gitlab ci pipelien
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: B0-silent, T10-release, A0-please_review, C1-low

#1838 fix failing gitlab ci pipelien
  .gitlab-ci.yml
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  scripts/ci/gitlab/pipeline/zombienet.yml
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, C1-low

#1840 [ci] Fix publish benchmark results
  scripts/ci/gitlab/pipeline/benchmarks.yml
  scripts/ci/gitlab/pipeline/publish.yml
Labels: B0-silent, A0-please_review, C1-low

#1841 [Backport] #1786 to fix failing zombienet test
  .gitlab-ci.yml
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1808 Companion for Substrate 12586
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D5-nicetohaveaudit ⚠️

#1851 bump txn versions
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, C1-low, D3-trivial 🧸

#1853 update substrate deps to the latest state
  Cargo.lock
Labels: B0-silent, T10-release, A0-please_review, C1-low, D3-trivial 🧸

#1857 [benchmarks] Update weights for collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, T10-release, T8-CGP, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#1852 Enable Docker section in the release notes
  scripts/ci/changelog/templates/docker_image.md.tera
  scripts/ci/changelog/templates/template.md.tera
Labels: A2-insubstantial, B0-silent, A0-please_review, C1-low

#1859 [benchmarks] Update weights for statemine/t
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, T10-release, T8-CGP, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#1870 [ci] fix buildah
  scripts/ci/gitlab/pipeline/publish.yml
Labels: B0-silent, A0-please_review, C1-low

#1871 [Backport] fix buildah (#1870)
  scripts/ci/gitlab/pipeline/publish.yml
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1876 Set `OnTimestampSet = Aura` in all runtimes
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1878 [Backport] of Set `OnTimestampSet = Aura` in all runtimes (#1876) to runtime release branch
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1873 [ci] Improve pipeline stopper
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#1872 Fix for xcm weight benchmarks generation
  parachains/runtimes/assets/statemine/src/weights/xcm/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/cumulus_pallet_xcmp_queue.rs
  scripts/benchmarks-ci.sh
Labels: B0-silent, A0-please_review, C1-low

#1881 companion for #12599
  Cargo.lock
Labels: B0-silent, A0-please_review, A4-companion, C1-low

#1885 bump rococo and penpal spec_version
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, C1-low, T5-parachains, T1-runtime, D3-trivial 🧸

#1886 [Backport] bump rococo and penpal spec_version (#1885)
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, T5-parachains, D3-trivial 🧸

#1889 [Backport] bump spec and txn versions from v9320
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1850 Use pallet-sudo extension `CheckOnylSudoAccount`
  Cargo.toml
  pallets/solo-to-para/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#1890 [Backport] weights from v9320 release branch
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1892 Remove 1 Parity Statemine bootnode that will be decommisioned
  parachains/chain-specs/statemine.json
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#1899 Companion for paritytech/substrate#12739
  Cargo.lock
  client/relay-chain-minimal-node/src/network.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1887 Remove 2 Parity statemint bootnodes from chainspec
  parachains/chain-specs/statemint.json
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#1869 Rename package to avoid name clash (#1716)
  Cargo.lock
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low

#1904 Correct issue link
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/xcm_config.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#1902 Collectives Alliance: Remove Founder role and veto call
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D3-trivial 🧸, X1-runtime

#1906 Allow try-runtime for contracts-rococo
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D3-trivial 🧸, X1-runtime

#1903 Remove av-store, av-distribution, chain-api subsystems from minimal node
  Cargo.lock
  client/relay-chain-minimal-node/Cargo.toml
  client/relay-chain-minimal-node/src/collator_overseer.rs
  client/relay-chain-minimal-node/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1910 Allow Sufficient Assets for XCM Fee Payment on Statemint #1884
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemine/tests/tests.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/statemint/tests/tests.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/tests/tests.rs
  primitives/utility/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, X1-runtime

#1898 Companion for Substrate 12740
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/tests/tests.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/tests/tests.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/tests/tests.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/Cargo.toml
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D3-trivial 🧸, X1-runtime

#1916 Companion for contracts: Replace cargo feature `unstable-interface` with config
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸
