Repository paritytech/cumulus, pull requests merged in 2022-02, with the labels that each got.

#940 merge from cumulus release branch inc extra commit
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/src/cli.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/genesis.rs
Labels: A0-pleasereview, B0-silent, M5-statemint, C1-low 📌

#941 Fix `--parachain-id` usage in README guide
  README.md
  polkadot-parachains/src/cli.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#943 ci: fix broken reference to rococo srtool digest
  .github/workflows/release-02_create-draft.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#944 ci: fix broken reference to rococo srtool digest (backport of #943)
  .github/workflows/release-02_create-draft.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#954 Update command for running benchmarks
  .github/ISSUE_TEMPLATE/release.md
Labels: A2-insubstantial, B0-silent, C1-low 📌

#951 New weights
  polkadot-parachains/statemine/src/weights/frame_system.rs
  polkadot-parachains/statemine/src/weights/pallet_assets.rs
  polkadot-parachains/statemine/src/weights/pallet_balances.rs
  polkadot-parachains/statemine/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemine/src/weights/pallet_multisig.rs
  polkadot-parachains/statemine/src/weights/pallet_proxy.rs
  polkadot-parachains/statemine/src/weights/pallet_session.rs
  polkadot-parachains/statemine/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemine/src/weights/pallet_utility.rs
  polkadot-parachains/statemint/src/weights/frame_system.rs
  polkadot-parachains/statemint/src/weights/pallet_assets.rs
  polkadot-parachains/statemint/src/weights/pallet_balances.rs
  polkadot-parachains/statemint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemint/src/weights/pallet_multisig.rs
  polkadot-parachains/statemint/src/weights/pallet_proxy.rs
  polkadot-parachains/statemint/src/weights/pallet_session.rs
  polkadot-parachains/statemint/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/weights/pallet_utility.rs
  polkadot-parachains/westmint/src/weights/frame_system.rs
  polkadot-parachains/westmint/src/weights/pallet_assets.rs
  polkadot-parachains/westmint/src/weights/pallet_balances.rs
  polkadot-parachains/westmint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/westmint/src/weights/pallet_multisig.rs
  polkadot-parachains/westmint/src/weights/pallet_proxy.rs
  polkadot-parachains/westmint/src/weights/pallet_session.rs
  polkadot-parachains/westmint/src/weights/pallet_timestamp.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, M5-statemint, C1-low 📌

#957 ci: fix publish-runtimes for parachains containing - in name
  .github/workflows/release-02_create-draft.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#931 Add Setter for XCMP QueueConfigData
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#960 ci: fix publish-runtimes for parachains containing - in name (v2) (backport of #959)
  .github/workflows/release-02_create-draft.yml
Labels: A0-pleasereview, A8-looksgood, B0-silent, C1-low 📌

#959 ci: fix publish-runtimes for parachains containing - in name (v2)
  .github/workflows/release-02_create-draft.yml
Labels: A0-pleasereview, A8-looksgood, B0-silent, C1-low 📌

#812 Ensure invulnerables have associated validator keys before they are set
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/tests.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#942 Return compressed PoV from collation
  Cargo.lock
  client/collator/Cargo.toml
  client/collator/src/lib.rs
  client/relay-chain-local/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#965 Add / Remove migrations
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, M5-statemint, C1-low 📌

#966 Bump transaction version for release 700
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#967 Update Substrate & Polkadot
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#972 CI: Check that rustdocs can be generated
  .gitlab-ci.yml
  client/consensus/aura/src/lib.rs
  client/network/src/lib.rs
  pallets/collator-selection/src/lib.rs
  pallets/parachain-system/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#977 Update Substrate & Polkadot
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#978 ci: fix bash quoting in docker ci
  .github/workflows/release-10_docker.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#970 Bump collator version
  Cargo.lock
  polkadot-parachains/Cargo.toml
Labels: A2-insubstantial, A8-backport, B0-silent, C1-low 📌

#974 collective flip migration removed, uniques added (#965)
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A8-backport, B0-silent, M5-statemint, C1-low 📌

#975 bump tx version (#966)
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A8-backport, B0-silent, M5-statemint, C1-low 📌

#981 Move XCM configurations out into its own module
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  parachain-template/runtime/src/xcm_config.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/shell/src/xcm_config.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/xcm_config.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/xcm_config.rs
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/xcm_config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#985 Update Polkadot & Substrate
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#987 Update rand to v0.8.5
  Cargo.lock
  client/pov-recovery/Cargo.toml
  pallets/collator-selection/Cargo.toml
  test/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#991 Fix Runtime Benchmarks Feature Flag in Parachain Template
  .gitlab-ci.yml
  parachain-template/node/Cargo.toml
Labels: B0-silent, Q0-trivial, C1-low 📌

#980 Add `canvas-kusama` runtime
  Cargo.lock
  Cargo.toml
  README.md
  docs/canvas-overview.svg
  polkadot-parachains/Cargo.toml
  polkadot-parachains/canvas-kusama/Cargo.toml
  polkadot-parachains/canvas-kusama/build.rs
  polkadot-parachains/canvas-kusama/src/constants.rs
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/rpc.rs
  polkadot-parachains/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#996 Fix parachain-template-runtime build fail
  parachain-template/runtime/Cargo.toml
Labels: B0-silent, Q0-trivial, C1-low 📌

#994 Move Canvas xcm config to its own module
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/canvas-kusama/src/xcm_config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1008 Fix relay chain node name
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1009 Canvas: Bump `spec_version` and `state_version`
  polkadot-parachains/canvas-kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#986 Remove migrations that have been executed
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1010 canvas: Add sudo
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/src/chain_spec.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#997 canvas: More refactoring
  polkadot-parachains/canvas-kusama/src/contracts.rs
  polkadot-parachains/canvas-kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1012 updating benchmarking script
  scripts/benchmarks.sh
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1011 canvas: Run migrations defined by `pallet-contracts`
  polkadot-parachains/canvas-kusama/src/contracts.rs
  polkadot-parachains/canvas-kusama/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1014 Bump `tokio` to 1.17.0
  Cargo.lock
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  test/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1015 Add dependabot config file
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1021 Dependabot: Make sure to ignore all the Substrate deps
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1026 Dependabot: Also ignore polkadot :grimaced:
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1034 Dependabot: A new round...
  .github/dependabot.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1032 Remove node-primitives
  Cargo.lock
  polkadot-parachains/canvas-kusama/Cargo.toml
  polkadot-parachains/canvas-kusama/src/constants.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/constants.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/constants.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/constants.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#993 Companion for substrate#10878
  Cargo.lock
  client/consensus/aura/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/src/service.rs
Labels: B0-silent, C1-low 📌, A7-companion

#1042 fix: map cli option `--runtime_cache_size`
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1047 Remove the last node-primitives leftover...
  Cargo.lock
  polkadot-parachains/canvas-kusama/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1043 Add Canvas runtime to release automation
  .github/workflows/release-02_create-draft.yml
  .github/workflows/srtool.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1013 Companion to "Updating scale to v3"
  Cargo.lock
  client/collator/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/common/Cargo.toml
  client/network/Cargo.toml
  client/network/src/lib.rs
  client/pov-recovery/Cargo.toml
  client/service/Cargo.toml
  pallets/aura-ext/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/dmp-queue/Cargo.toml
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/Cargo.toml
  pallets/session-benchmarking/Cargo.toml
  pallets/solo-to-para/Cargo.toml
  pallets/xcm/Cargo.toml
  pallets/xcm/src/lib.rs
  pallets/xcmp-queue/Cargo.toml
  pallets/xcmp-queue/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/pallets/template/Cargo.toml
  parachain-template/runtime/Cargo.toml
  polkadot-parachains/Cargo.toml
  polkadot-parachains/canvas-kusama/Cargo.toml
  polkadot-parachains/pallets/parachain-info/Cargo.toml
  polkadot-parachains/pallets/ping/Cargo.toml
  polkadot-parachains/parachains-common/Cargo.toml
  polkadot-parachains/rococo-parachain/Cargo.toml
  polkadot-parachains/seedling/Cargo.toml
  polkadot-parachains/shell/Cargo.toml
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/westmint/Cargo.toml
  primitives/core/Cargo.toml
  primitives/parachain-inherent/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/utility/Cargo.toml
  test/client/Cargo.toml
  test/relay-sproof-builder/Cargo.toml
  test/runtime/Cargo.toml
  test/service/Cargo.toml
Labels: B0-silent, C1-low 📌, A7-companion
