Repository paritytech/cumulus, pull requests merged in 2022-12, with the labels that each got.

#1927 Remove block request, state request, light client request-response protocols from minimal node
  Cargo.lock
  client/relay-chain-minimal-node/Cargo.toml
  client/relay-chain-minimal-node/src/network.rs
Labels: B0-silent, A0-please_review, C1-low

#1932 update deps with the asset destroy changes in substrate and polkadot
  Cargo.lock
  client/cli/Cargo.toml
  client/collator/Cargo.toml
  client/consensus/aura/Cargo.toml
  client/consensus/common/Cargo.toml
  client/consensus/relay-chain/Cargo.toml
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-minimal-node/Cargo.toml
  client/relay-chain-rpc-interface/Cargo.toml
  client/service/Cargo.toml
  pallets/aura-ext/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/dmp-queue/Cargo.toml
  pallets/parachain-system/Cargo.toml
  pallets/session-benchmarking/Cargo.toml
  pallets/solo-to-para/Cargo.toml
  pallets/xcm/Cargo.toml
  pallets/xcmp-queue/Cargo.toml
  parachain-template/node/Cargo.toml
  parachain-template/pallets/template/Cargo.toml
  parachain-template/runtime/Cargo.toml
  parachains/common/Cargo.toml
  parachains/pallets/parachain-info/Cargo.toml
  parachains/pallets/ping/Cargo.toml
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/test-utils/Cargo.toml
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/starters/seedling/Cargo.toml
  parachains/runtimes/starters/shell/Cargo.toml
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/rococo-parachain/Cargo.toml
  polkadot-parachain/Cargo.toml
  primitives/core/Cargo.toml
  primitives/parachain-inherent/Cargo.toml
  primitives/timestamp/Cargo.toml
  primitives/utility/Cargo.toml
  scripts/ci/gitlab/pipeline/publish.yml
  test/client/Cargo.toml
  test/relay-sproof-builder/Cargo.toml
  test/relay-validation-worker-provider/Cargo.toml
  test/runtime/Cargo.toml
  test/service/Cargo.toml
Labels: B0-silent, T10-release, A0-please_review, C1-low

#1926 bump rococo and penpal spec_version
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, C1-low, T5-parachains, D3-trivial 🧸

#1940 Provisioner polkadot companion
  Cargo.lock
  client/consensus/aura/src/lib.rs
  client/consensus/relay-chain/src/import_queue.rs
  client/consensus/relay-chain/src/lib.rs
  primitives/parachain-inherent/src/client_side.rs
  primitives/parachain-inherent/src/mock.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸, X1-runtime

#1942 bump transaction_versions client
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, T8-CGP, A0-please_review, C1-low, D3-trivial 🧸

#1945 [benchmarks] Update weights for collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, T10-release, T8-CGP, A0-please_review, C1-low, T1-runtime

#1914 Add collectives-polkadot final raw chainspec
  parachains/chain-specs/collectives-polkadot.json
Labels: A0-please_review, B1-note_worthy, C3-medium, D3-trivial 🧸, X1-runtime

#1950 [Backport] weights 9330 from runtime release branch
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, T10-release, T8-CGP, A0-please_review, A6-backport, C1-low, T0-node, D3-trivial 🧸

#1944 Companion of Substrate PR 12837
  .github/dependabot.yml
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#1966 add collective runtime upgrade to the checklist
  .github/ISSUE_TEMPLATE/release-runtime.md
Labels: B0-silent, T10-release, A0-please_review, C1-low, D3-trivial 🧸

#1969 `zombienet` store node's logs as artifacts
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: B0-silent, A0-please_review, C1-low

#1959 Backport collective weights from v9330 to master
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1956 [Backport] version bumps from 9330
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1967 [ci] new ci runners
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#1971 [benchmarks] backport of statemine/t weights to master (#1946)
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1970 Companion for paritytech/substrate#12868
  Cargo.lock
  pallets/dmp-queue/src/lib.rs
  pallets/dmp-queue/src/migration.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/migration.rs
  pallets/xcmp-queue/src/tests.rs
  parachain-template/runtime/src/lib.rs
  parachain-template/runtime/src/weights/block_weights.rs
  parachain-template/runtime/src/weights/extrinsic_weights.rs
  parachain-template/runtime/src/weights/paritydb_weights.rs
  parachain-template/runtime/src/weights/rocksdb_weights.rs
  parachains/common/src/lib.rs
  parachains/runtimes/assets/statemine/src/weights/block_weights.rs
  parachains/runtimes/assets/statemine/src/weights/extrinsic_weights.rs
  parachains/runtimes/assets/statemine/src/weights/paritydb_weights.rs
  parachains/runtimes/assets/statemine/src/weights/rocksdb_weights.rs
  parachains/runtimes/assets/statemint/src/weights/block_weights.rs
  parachains/runtimes/assets/statemint/src/weights/extrinsic_weights.rs
  parachains/runtimes/assets/statemint/src/weights/paritydb_weights.rs
  parachains/runtimes/assets/statemint/src/weights/rocksdb_weights.rs
  parachains/runtimes/assets/westmint/src/weights/block_weights.rs
  parachains/runtimes/assets/westmint/src/weights/extrinsic_weights.rs
  parachains/runtimes/assets/westmint/src/weights/paritydb_weights.rs
  parachains/runtimes/assets/westmint/src/weights/rocksdb_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/block_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/extrinsic_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/paritydb_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/rocksdb_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/block_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/extrinsic_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/paritydb_weights.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/rocksdb_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/block_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/extrinsic_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/paritydb_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/rocksdb_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/block_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/extrinsic_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/paritydb_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/rocksdb_weights.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/penpal/src/weights/block_weights.rs
  parachains/runtimes/testing/penpal/src/weights/extrinsic_weights.rs
  parachains/runtimes/testing/penpal/src/weights/paritydb_weights.rs
  parachains/runtimes/testing/penpal/src/weights/rocksdb_weights.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1891 Explicit recovery for announced candidate blocks
  Cargo.lock
  client/consensus/common/Cargo.toml
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/common/src/tests.rs
  client/pov-recovery/src/active_candidate_recovery.rs
  client/pov-recovery/src/lib.rs
  client/service/Cargo.toml
  client/service/src/lib.rs
  primitives/core/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D2-notlive 💤

#1976 Collectives runtime: weight and fee info rpc for Call
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D3-trivial 🧸, X1-runtime

#1930 Companion for paritytech/substrate#12764
  Cargo.lock
  client/pov-recovery/src/lib.rs
  client/relay-chain-minimal-node/src/network.rs
  client/service/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1955 add test onto statemint as well as statemine now (#1954)
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#1985 [ci] use external repo for check-labels
  .github/workflows/check-D-labels.yml
  .github/workflows/check-label-rules.yaml
  .github/workflows/check-labels-old.yml
  .github/workflows/check-labels.yml
  CODEOWNERS
  docs/documentation.md
  scripts/ci/ruled_labels/specs.yaml
  scripts/ci/ruled_labels/test.sh
  scripts/ci/ruled_labels/tests.yaml
Labels: B0-silent, A0-please_review, C1-low

#1943 Introduce migrations for inactive balances
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1979 Collectives chain integration tests
  parachains/integration-tests/collectives/0_xcm/0_init.yml
  parachains/integration-tests/collectives/0_xcm/1_teleport.yml
  parachains/integration-tests/collectives/0_xcm/2_reserve.yml
  parachains/integration-tests/collectives/1_alliance/0_join_alliance_fails.yml
  parachains/integration-tests/collectives/1_alliance/1_init_alliance.yml
  parachains/integration-tests/collectives/1_alliance/2_join_alliance_fails.yml
  parachains/integration-tests/collectives/1_alliance/3_kick_member.yml
  parachains/integration-tests/collectives/config.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1986 [ci] Add variable to disable selected jobs
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#1880 Allow to specify multiple relay chain RPC urls for collator node
  Cargo.lock
  client/cli/src/lib.rs
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  client/relay-chain-minimal-node/src/collator_overseer.rs
  client/relay-chain-minimal-node/src/lib.rs
  client/relay-chain-rpc-interface/Cargo.toml
  client/relay-chain-rpc-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
  client/service/Cargo.toml
  client/service/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
  zombienet/tests/0006-rpc_collator_builds_blocks.feature
  zombienet/tests/0006-rpc_collator_builds_blocks.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1997 companion for try-runtime revamp
  Cargo.lock
  parachain-template/node/Cargo.toml
  parachain-template/node/src/command.rs
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  polkadot-parachain/src/command.rs
Labels: B0-silent, A0-please_review, C1-low, D2-notlive 💤

#1998 Remove tests that are covered by zombienet
  client/network/tests/sync_blocks_from_tip_without_connected_collator.rs
  client/pov-recovery/tests/pov_recovery.rs
  test/service/tests/full_node_catching_up.rs
  test/service/tests/migrate_solo_to_para.rs
  test/service/tests/runtime_upgrade.rs
Labels: B0-silent, A0-please_review, C1-low

#1559 Limit number of blocks per level (2nd attempt)
  Cargo.lock
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/Cargo.toml
  client/consensus/common/src/level_monitor.rs
  client/consensus/common/src/lib.rs
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/common/src/tests.rs
  client/consensus/relay-chain/src/import_queue.rs
  client/consensus/relay-chain/src/lib.rs
  client/pov-recovery/src/active_candidate_recovery.rs
  client/pov-recovery/src/lib.rs
  client/service/Cargo.toml
  client/service/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1984 Expect less chaos: use explicit call indices
  pallets/collator-selection/src/lib.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/solo-to-para/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  parachain-template/pallets/template/src/lib.rs
  parachains/pallets/ping/src/lib.rs
  test/runtime/src/test_pallet.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#1977 BlockId removal: refactor: HeaderBackend::header
  Cargo.lock
  client/collator/src/lib.rs
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  pallets/parachain-system/src/validate_block/tests.rs
  primitives/timestamp/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1999 Bridge hub kusama fine-tuning before release
  parachains/chain-specs/bridge-hub-kusama.json
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  scripts/benchmarks-ci.sh
  scripts/ci/gitlab/pipeline/benchmarks.yml
  scripts/create_bridge_hub_kusama_spec.sh
Labels: B0-silent, A0-please_review, C3-medium, T1-runtime, T9-bridges

#2007 BlockId removal: refactor: HeaderBackend::status
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2014 fix deps duplications in Cargo.lock
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1947 Companion for Substrate 12307
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D1-audited 👍, T1-runtime

#2018 bump txn versions
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, C1-low, D3-trivial 🧸

#2020 Backport: bump txn versions (#2018) to runtimes release branch
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2019 Backport: bump txn versions (#2018)
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2026 [benchmarks] pr with weights bridge-hubs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low

#2025 [benchmarks] pr with weights Collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, A0-please_review, C1-low

#2027 [benchmarks] pr with weights Statemine/t
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low

#1865 Companion: Accept Kusama StakingAdmin origin
  parachains/runtimes/assets/statemine/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C3-medium, D9-needsaudit 👮, T1-runtime

#2031 Release 9360 - Remove Statemint Stale Migrations
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2030 Alliance: remove veto weight func
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2033 Backport: remove 9330 migrations from statemint series (#2031) to node branch
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#2034 Backport: remove 9330 migrations from statemint series (#2031) to the source branhc
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#2036 Collectives parachain integration tests update
  parachains/integration-tests/collectives/0_xcm/1_teleport.yml
  parachains/integration-tests/collectives/1_alliance/1_init_alliance.yml
  parachains/integration-tests/collectives/1_alliance/3_kick_member.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸
