Repository paritytech/cumulus, pull requests merged in 2022-05, with the labels that each got.

#1234 Update Substrate & Polkadot
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1236 Companion for Force Batch
  Cargo.lock
  polkadot-parachains/statemine/src/weights/pallet_utility.rs
  polkadot-parachains/statemint/src/weights/pallet_utility.rs
  polkadot-parachains/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1237 CI deps ugrade
  .github/workflows/check-labels.yml
  .github/workflows/docs.yml
  .github/workflows/extrinsic-ordering-check-from-bin.yml
  .github/workflows/quick-check.yml
  .github/workflows/release-01_rc-automation.yml
  .github/workflows/release-02_create-draft.yml
  .github/workflows/release-10_docker-manual.yml
  .github/workflows/release-10_docker.yml
  .github/workflows/srtool.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1239 [ci] update review rules
  .github/pr-custom-review.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1242 Companion for contracts dos vector fix
  Cargo.lock
  polkadot-parachains/canvas-kusama/src/contracts.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A7-companion

#823 companion #8738 (jsonrpsee)
  Cargo.lock
  client/network/tests/sync_blocks_from_tip_without_connected_collator.rs
  client/pov-recovery/tests/pov_recovery.rs
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-rpc-interface/Cargo.toml
  pallets/parachain-system/Cargo.toml
  parachain-template/node/Cargo.toml
  parachain-template/node/src/rpc.rs
  parachain-template/node/src/service.rs
  polkadot-parachains/Cargo.toml
  polkadot-parachains/src/rpc.rs
  polkadot-parachains/src/service.rs
  test/service/Cargo.toml
  test/service/src/lib.rs
  test/service/tests/full_node_catching_up.rs
  test/service/tests/migrate_solo_to_para.rs
  test/service/tests/runtime_upgrade.rs
Labels: B0-silent, C1-low 📌, A7-companion

#1253 companion 11395
  Cargo.lock
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-rpc-interface/Cargo.toml
  parachain-template/node/Cargo.toml
  polkadot-parachains/Cargo.toml
  test/service/Cargo.toml
Labels: B0-silent, C1-low 📌

#1256 Companion to #11389 (Uniques Rename)
  Cargo.lock
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
Labels: B2-breaksapi, B7-runtimenoteworthy, C1-low 📌

#1264 Companion for Polkadot #5536 (Remove Duplicate Traits)
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1262 Companion for Substrate #10719 (Into Account Truncating)
  Cargo.lock
  pallets/collator-selection/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1261 Companion for bounded contracts storage
  Cargo.lock
  polkadot-parachains/canvas-kusama/src/contracts.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌, A7-companion

#1267 Companion to #11441 (Uniques Max Supply)
  Cargo.lock
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
Labels: A0-pleasereview, B7-runtimenoteworthy, C1-low 📌, A7-companion

#1270 add GHA checks to dependabot
  .github/dependabot.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1158 Create binary for cumulus testing node #1128
  Cargo.lock
  client/cli/src/lib.rs
  test/service/Cargo.toml
  test/service/src/cli.rs
  test/service/src/lib.rs
  test/service/src/main.rs
  zombienet_tests/0001-sync_blocks_from_tip_without_connected_collator.feature
  zombienet_tests/0001-sync_blocks_from_tip_without_connected_collator.toml
  zombienet_tests/0002-pov_recovery.feature
  zombienet_tests/0002-pov_recovery.toml
  zombienet_tests/0003-test_full_node_catching_up.feature
  zombienet_tests/0003-test_full_node_catching_up.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1277 Fix Cumulus Compile (into_account_truncating)
  Cargo.lock
  test/service/src/main.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1281 Companion for polkadot#5569
  Cargo.lock
  client/collator/src/lib.rs
  parachain-template/node/src/rpc.rs
  polkadot-parachain/src/rpc.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1283 Runtime version bump to 922
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-pleasereview, B0-silent, F9-release 🏷, C1-low 📌

#1279 Use API for pr-custom-review
  .github/workflows/pr-custom-review.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1287 Backport of version bumps to v0.9.22/9220 from master
  Cargo.lock
  polkadot-parachains/Cargo.toml
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, A8-backport, B0-silent, C1-low 📌

#1282 Runtime Documentation
  parachains/README.md
  parachains/runtimes/assets/README.md
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-pleasereview, B0-silent, F5-documentation 📄, C1-low 📌

#1289 sudo was removed from statemine/t but we were still pulling in the crate.
  Cargo.lock
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemint/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1296 deleted unnecessary repo checkout to fix fetch binary step
  .github/workflows/extrinsic-ordering-check-from-bin.yml
Labels: A0-pleasereview, B0-silent, F9-release 🏷, C1-low 📌, ci

#1294 contracts: Update bootnodes
  parachains/chain-specs/contracts-rococo.json
  polkadot-parachain/src/chain_spec.rs
Labels: A0-pleasereview, B0-silent, M8-contracts, C1-low 📌

#1301 CI change rule to run benchmarks
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, ci

#1302 update weights for v9220
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B1-releasenotes, C1-low 📌

#1299 bringing back repo checkout and adding a temp dir to avoid name duplication between binary and repo dir
  .github/workflows/extrinsic-ordering-check-from-bin.yml
Labels: A0-pleasereview, B0-silent, F9-release 🏷, C1-low 📌, ci

#1306 use RuntimeDebug
  pallets/xcm/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1305 Companion to Substrate #11490
  Cargo.lock
  pallets/parachain-system/src/migration.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, A7-companion

#1307 Ensure we send the correct polkadot node version to telemetry
  Cargo.lock
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌
