Repository paritytech/cumulus, pull requests merged in 2022-09, with the labels that each got.

#1454 [Feature] Add XCM benchmark weights to Statemint and Statemine
  Cargo.lock
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/src/weights/mod.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/weights/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/weights/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  scripts/benchmarks-ci.sh
  templates/xcm-bench-template.hbs
Labels: A0-please_review, B1-note_worthy, C1-low, X1-runtime

#1551 Update Cumulus to Latest Substrate and Polkadot Master
  Cargo.lock
  pallets/aura-ext/Cargo.toml
  pallets/dmp-queue/Cargo.toml
  pallets/parachain-system/Cargo.toml
  pallets/solo-to-para/Cargo.toml
  pallets/xcm/Cargo.toml
  pallets/xcmp-queue/Cargo.toml
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  parachains/pallets/parachain-info/Cargo.toml
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: B0-silent, A0-please_review, B1-note_worthy, C1-low, X1-runtime

#1574 9270 Backport of Align versions for runtimes (#1517)
  Cargo.lock
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: B0-silent, A6-backport, C1-low

#1587 Companion for https://github.com/paritytech/substrate/pull/12147
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/tests/common.rs
  polkadot-parachain/tests/purge_chain_works.rs
  test/service/src/cli.rs
Labels: B0-silent, A0-please_review, C1-low

#1590 Companion for paritytech/substrate#12157
  Cargo.lock
  pallets/collator-selection/src/weights.rs
  pallets/xcmp-queue/src/weights.rs
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
  templates/xcm-bench-template.hbs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1575 9270 Backport / Integration tests Statemine & Statemint (#1526)
  parachains/integration-tests/statemine/xcm/0_init.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/xcm/0_init.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A6-backport, C1-low

#1593 Companion for substrate#12179
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
Labels: B0-silent, A0-please_review, C1-low, X1-runtime

#1597 fix release report generation script
  scripts/ci/changelog/bin/changelog
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1599 fix release report generation script
  scripts/ci/changelog/bin/changelog
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1602 Add right feature flags to `relay-chain-inprocess-interface`
  client/relay-chain-inprocess-interface/Cargo.toml
Labels: A2-insubstantial, C1-low

#1601 Companion for paritytech/substrate#12183
  Cargo.lock
  pallets/dmp-queue/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  parachain-template/runtime/src/weights/block_weights.rs
  parachain-template/runtime/src/weights/extrinsic_weights.rs
  parachain-template/runtime/src/weights/paritydb_weights.rs
  parachain-template/runtime/src/weights/rocksdb_weights.rs
  parachains/runtimes/assets/statemine/src/weights/block_weights.rs
  parachains/runtimes/assets/statemine/src/weights/extrinsic_weights.rs
  parachains/runtimes/assets/statemine/src/weights/paritydb_weights.rs
  parachains/runtimes/assets/statemine/src/weights/rocksdb_weights.rs
  parachains/runtimes/assets/statemint/src/weights/block_weights.rs
  parachains/runtimes/assets/statemint/src/weights/extrinsic_weights.rs
  parachains/runtimes/assets/statemint/src/weights/paritydb_weights.rs
  parachains/runtimes/assets/statemint/src/weights/rocksdb_weights.rs
  parachains/runtimes/assets/westmint/src/weights/block_weights.rs
  parachains/runtimes/assets/westmint/src/weights/extrinsic_weights.rs
  parachains/runtimes/assets/westmint/src/weights/paritydb_weights.rs
  parachains/runtimes/assets/westmint/src/weights/rocksdb_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/block_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/extrinsic_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/paritydb_weights.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/rocksdb_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/block_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/extrinsic_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/paritydb_weights.rs
  parachains/runtimes/contracts/contracts-rococo/src/weights/rocksdb_weights.rs
  parachains/runtimes/testing/penpal/src/weights/block_weights.rs
  parachains/runtimes/testing/penpal/src/weights/extrinsic_weights.rs
  parachains/runtimes/testing/penpal/src/weights/paritydb_weights.rs
  parachains/runtimes/testing/penpal/src/weights/rocksdb_weights.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1594 Mock epoch index and randomness in SproofBuilder (for testing)
  primitives/parachain-inherent/src/mock.rs
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1605 Common version pattern for Collectives runtime
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1606 Common version pattern for Collectives runtime
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1612 runtimes version to 9290
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1563 Companion for #11981
  Cargo.lock
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/solo-to-para/src/lib.rs
  pallets/xcm/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  pallets/xcmp-queue/src/tests.rs
  parachain-template/pallets/template/src/lib.rs
  parachain-template/pallets/template/src/mock.rs
  parachain-template/runtime/src/lib.rs
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/impls.rs
  parachains/common/src/xcm_config.rs
  parachains/pallets/ping/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/starters/shell/src/xcm_config.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/client/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1610 Companion for paritytech/substrate#12219
  Cargo.lock
  client/consensus/aura/src/import_queue.rs
  pallets/collator-selection/src/lib.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/solo-to-para/src/lib.rs
  parachain-template/node/src/service.rs
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/src/service.rs
  test/runtime/src/lib.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1607 Co #11976: Enable rust features
  Cargo.lock
  parachain-template/node/src/command.rs
  parachain-template/runtime/Cargo.toml
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/testing/penpal/Cargo.toml
  polkadot-parachain/src/command.rs
  polkadot-parachain/tests/benchmark_storage_works.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1629 Don't panic.
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1630 Don't panic backported to release branch
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1631 Westmint don't panic.
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1595 Companion: contracts: Use `WeakBoundedVec` for instrumented code
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: A0-please_review, A4-companion, B1-note_worthy, C1-low, X1-runtime, D2-notlive 💤

#1582 [ci] build runtime only if runtime files were changed
  .gitlab-ci.yml
Labels: B0-silent, A3-in_progress, C1-low

#1639 [Fix] Weight calculations for Wild -> affects teleports
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A0-please_review, C1-low, X1-runtime

#1640 Revert "[Fix] Weight calculations for Wild -> affects teleports"
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A0-please_review, C1-low

#1642 [ci] Disable auto-fmt and revert cancel-pipeline
  .gitlab-ci.yml
Labels: B0-silent, A3-in_progress, C1-low

#1641 [Fix] Hardcode teleport weight until XCM pallet is fixed
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, X1-runtime

#1645 cherrypick teleport xcm fix to node rel branch
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1644 Cherry pick teleport xcm fix to runtime release branch
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1646 fix a wrong path to Extrinsic Ordering ci script
  .github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1649 Cherry pick transaction_version from master
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#1628 Rename Origin
  Cargo.lock
  client/service/src/lib.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  pallets/collator-selection/src/tests.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  pallets/xcmp-queue/src/tests.rs
  parachain-template/pallets/template/src/mock.rs
  parachain-template/pallets/template/src/tests.rs
  parachain-template/runtime/src/lib.rs
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/impls.rs
  parachains/pallets/ping/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/test-utils/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/starters/shell/src/xcm_config.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#1653 [benchmarks] Update weights for collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1651 [Fix] Deposit weight hardcoded to pre-bench value
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, X1-runtime

#1655 cherrypick deposit asset xcm fix to node rel branch
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1656 cherrypick deposit asset xcm fix to runtime rel branch
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1654 Ensure that inherents are first and unsigned
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/parachain-system/src/validate_block/tests.rs
Labels: B0-silent, A0-please_review, C1-low

#1658 Fix failing weights jobs
  .gitlab-ci.yml
Labels: B0-silent, T3-release, A0-please_review, C1-low

#1561 Companion for: Make automatic storage deposits resistant against changing deposit prices
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: A0-please_review, A4-companion, B1-note_worthy, C1-low, X1-runtime

#1660 [benchmarks] Update weights for collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1673 Update substrate dependencies
  Cargo.lock
Labels: B0-silent, T3-release, A0-please_review, C1-low

#1674 Update substrate dependencies
  Cargo.lock
  pallets/parachain-system/src/validate_block/tests.rs
Labels: B0-silent, T3-release, A0-please_review, C1-low

#1676 update deps and bump version
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T3-release, A0-please_review, C1-low, D3-trivial 🧸

#1667 Companion for #12283 (Anon -> Pure Proxy)
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
Labels: B1-note_worthy, C1-low, X1-runtime, D3-trivial 🧸

#1672 fix weights PR generation
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1679 Small cosmetic nits
  Cargo.lock
  Cargo.toml
  client/relay-chain-inprocess-interface/Cargo.toml
  client/service/src/lib.rs
  pallets/parachain-system/src/validate_block/tests.rs
  pallets/xcm/Cargo.toml
  parachains/common/Cargo.toml
  parachains/pallets/ping/Cargo.toml
  primitives/utility/Cargo.toml
Labels: B0-silent, C1-low

#1617 Companion - Independence for Slot-based algorithms from timestamp
  Cargo.lock
  client/consensus/aura/src/lib.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
Labels: B0-silent, A0-please_review, C1-low

#1613 Companion for substrate#11983.
  Cargo.lock
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1681 Update integration test v0.9.29
  parachains/integration-tests/statemine/xcm/1_dmp.yml
  parachains/integration-tests/statemine/xcm/2_ump.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/xcm/1_dmp.yml
  parachains/integration-tests/statemint/xcm/2_ump.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A0-please_review, C1-low

#1661 Companion for paritytech/substrate#12264
  .gitlab-ci.yml
  Cargo.lock
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1689 Update integration-tests
  parachains/integration-tests/statemine/xcm/1_dmp.yml
  parachains/integration-tests/statemine/xcm/2_ump.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/xcm/1_dmp.yml
  parachains/integration-tests/statemint/xcm/2_ump.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A0-please_review, C1-low

#1693 backport: add current time in milis to the branch name (#1658)
  .gitlab-ci.yml
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1691 backport: set xcm weights template (#1643)
  scripts/benchmarks-ci.sh
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1695 backport: update integration tests
  parachains/integration-tests/statemine/xcm/1_dmp.yml
  parachains/integration-tests/statemine/xcm/2_ump.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/xcm/1_dmp.yml
  parachains/integration-tests/statemint/xcm/2_ump.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1690 backport: Bump crate versions
  Cargo.lock
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A6-backport, C1-low, D3-trivial 🧸

#1680 Removed unused deps with `cargo machete`
  Cargo.lock
  client/collator/Cargo.toml
  client/consensus/common/Cargo.toml
  client/consensus/relay-chain/Cargo.toml
  client/network/Cargo.toml
  client/pov-recovery/Cargo.toml
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-interface/Cargo.toml
  client/relay-chain-rpc-interface/Cargo.toml
  client/service/Cargo.toml
  pallets/aura-ext/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/dmp-queue/Cargo.toml
  pallets/parachain-system/Cargo.toml
  pallets/solo-to-para/Cargo.toml
  pallets/xcm/Cargo.toml
  parachain-template/node/Cargo.toml
  parachain-template/pallets/template/Cargo.toml
  parachain-template/runtime/Cargo.toml
  parachains/common/Cargo.toml
  parachains/pallets/parachain-info/Cargo.toml
  parachains/pallets/ping/Cargo.toml
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/starters/seedling/Cargo.toml
  parachains/runtimes/starters/shell/Cargo.toml
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/rococo-parachain/Cargo.toml
  polkadot-parachain/Cargo.toml
  primitives/core/Cargo.toml
  primitives/utility/Cargo.toml
  test/runtime/Cargo.toml
  test/service/Cargo.toml
Labels: B0-silent, C1-low

#1603 Polkadot Collectives chain spec
  parachains/chain-specs/collectives-polkadot.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸
