Repository paritytech/cumulus, pull requests merged in 2022-10, with the labels that each got.

#1712 Westend Collectives chain spec
  parachains/chain-specs/collectives-westend.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1683 Update README.md
  README.md
Labels: A2-insubstantial, B0-silent, C1-low

#1715 Update integration tests
  pallets/parachain-system/src/validate_block/tests.rs
  parachains/integration-tests/statemine/config.toml
  parachains/integration-tests/statemine/xcm/0_init.yml
  parachains/integration-tests/statemine/xcm/1_dmp.yml
  parachains/integration-tests/statemine/xcm/2_ump.yml
  parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemine/xcm/4_hrmp.yml
  parachains/integration-tests/statemint/config.toml
  parachains/integration-tests/statemint/xcm/0_init.yml
  parachains/integration-tests/statemint/xcm/1_dmp.yml
  parachains/integration-tests/statemint/xcm/2_ump.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A0-please_review, C1-low

#1718 Update IT test ports
  parachains/integration-tests/statemint/xcm/0_init.yml
  parachains/integration-tests/statemint/xcm/1_dmp.yml
  parachains/integration-tests/statemint/xcm/2_ump.yml
  parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/statemint/xcm/4_hrmp.yml
Labels: B0-silent, A0-please_review, C1-low

#1685 Companion: Remove contracts RPC
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  parachains/common/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/rpc.rs
  polkadot-parachain/src/service.rs
  test/runtime/src/lib.rs
Labels: A4-companion, B1-note_worthy, C1-low, X0-node, D2-notlive 💤

#1714 Minor fix of pallet-collator-selection benchmark error
  pallets/collator-selection/src/benchmarking.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1727 Fix target of some Matrix notifications
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-30_create-draft.yml
  .github/workflows/release-99_bot-announce.yml
Labels: B0-silent, A0-please_review, C1-low

#1729 Bridge-Hub Rococo Chainspec
  parachains/chain-specs/bridge-hub-rococo.json
Labels: B0-silent

#1731 fmt
  parachain-template/runtime/src/lib.rs
  parachains/common/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1733 [ci] add fmt check
  .github/workflows/fmt-check.yml
Labels: B0-silent, A0-please_review, C1-low

#1726 Companion for contracts WeightV2
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D2-notlive 💤

#1730 Add protoc
  .github/workflows/docs.yml
Labels: B0-silent, A0-please_review, C1-low, I6-documentation

#1735 Fix protoc install
  .github/workflows/docs.yml
Labels: B0-silent, A0-please_review, C1-low

#1585 Enable collation via RPC relay chain node
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  client/cli/src/lib.rs
  client/network/src/tests.rs
  client/pov-recovery/Cargo.toml
  client/pov-recovery/src/lib.rs
  client/pov-recovery/tests/pov_recovery.rs
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-minimal-node/Cargo.toml
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  client/relay-chain-minimal-node/src/collator_overseer.rs
  client/relay-chain-minimal-node/src/lib.rs
  client/relay-chain-minimal-node/src/network.rs
  client/relay-chain-rpc-interface/Cargo.toml
  client/relay-chain-rpc-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
  client/service/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/cli.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
  test/service/Cargo.toml
  test/service/src/cli.rs
  test/service/src/lib.rs
  test/service/src/main.rs
  zombienet_tests/0006-rpc_collator_builds_blocks.feature
  zombienet_tests/0006-rpc_collator_builds_blocks.toml
Labels: A0-please_review, B1-note_worthy, C1-low, X0-node

#1749 Companion for paritytech/polkadot#6117
  Cargo.lock
  client/relay-chain-minimal-node/Cargo.toml
  client/relay-chain-minimal-node/src/network.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1758 Companion for paritytech/substrate#12480
  Cargo.lock
  client/relay-chain-minimal-node/src/network.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1760 BlockId removal refactor: Backend::state_at
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1766 Companion for paritytech/substrate#12489
  Cargo.lock
  client/relay-chain-minimal-node/src/network.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1768 GHA updates and pin
  .github/workflows/check-labels.yml
  .github/workflows/docs.yml
  .github/workflows/fmt-check.yml
  .github/workflows/release-01_branch-check.yml
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
  .github/workflows/release-21_extrinsic-ordering-check-from-two.yml
  .github/workflows/release-30_create-draft.yml
  .github/workflows/release-50_docker-manual.yml
  .github/workflows/release-50_docker.yml
  .github/workflows/srtool.yml
Labels: B0-silent, A0-please_review, C1-low

#1762 Runtime release checklist template update
  .github/ISSUE_TEMPLATE/release-runtime.md
Labels: A0-please_review

#1748 contracts: Reduce session length and enable unstable interfaces
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, X1-runtime, D2-notlive 💤

#1745 Update clap to version 4
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/cli.rs
  test/service/Cargo.toml
  test/service/src/cli.rs
Labels: B0-silent, A0-please_review, C1-low

#1770 BlockId removal: refactor: StorageProvider
  Cargo.lock
  primitives/parachain-inherent/src/mock.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1777 Reduce parachain template cognitive complexity
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
Labels: B0-silent, A0-please_review, C1-low

#1711 pov-recovery: try connect to validators
  .gitlab-ci.yml
  zombienet_tests/0002-pov_recovery.feature
  zombienet_tests/0002-pov_recovery.toml
  zombienet_tests/register-para.js
Labels: A2-insubstantial, B0-silent, C1-low

#1701 [ci] Split .gitlab-ci.yml
  .github/pr-custom-review.yml
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/benchmarks.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/integration_tests.yml
  scripts/ci/gitlab/pipeline/publish.yml
  scripts/ci/gitlab/pipeline/test.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: B0-silent, A0-please_review, C1-low

#1780 bump transaction versions
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, T3-release, A0-please_review, C1-low, D3-trivial 🧸

#1785 [ci] Fix broken ci, move zombienet job
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: B0-silent, A0-please_review, C1-low

#1759 Co #12341: Use `try-runtime` feature
  Cargo.lock
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  parachain-template/runtime/Cargo.toml
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/starters/shell/Cargo.toml
  parachains/runtimes/testing/penpal/Cargo.toml
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/cli.rs
  polkadot-parachain/src/command.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1779 BlockId removal: refactor: Finalizer
  Cargo.lock
  client/consensus/common/src/parachain_consensus.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1788 Add link to the weight comparison tool for weights PRs
  scripts/ci/create-benchmark-pr.sh
  scripts/ci/gitlab/pipeline/benchmarks.yml
Labels: A2-insubstantial, B0-silent, C1-low

#1782 Single ParachainBlockImport instance
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/src/lib.rs
  client/consensus/relay-chain/src/import_queue.rs
  client/consensus/relay-chain/src/lib.rs
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#1755 Fix a few migration issues with 2D weights
  Cargo.lock
  pallets/dmp-queue/src/lib.rs
  pallets/dmp-queue/src/migration.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/migration.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/migration.rs
  pallets/xcmp-queue/src/tests.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#1794 contracts: Companion for offchain indeterminism
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D2-notlive 💤

#1793 Companion for #12457 (Bounded Multisig)
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: B0-silent, C1-low, D3-trivial 🧸

#1805 Co #12558: Update `pallet-multisig` benches
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  test/relay-sproof-builder/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#1806 Companion for update `wasm-opt`
  Cargo.lock
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#1807 Add RPC nodes to pov-recovery test
  zombienet_tests/0002-pov_recovery.feature
  zombienet_tests/0002-pov_recovery.toml
Labels: B0-silent, A0-please_review, C1-low
