Repository paritytech/cumulus, pull requests merged in 2022-03, with the labels that each got.

#1058 Add wasmtime feature to all parachain clients
  parachain-template/node/Cargo.toml
  polkadot-parachains/Cargo.toml
  test/client/Cargo.toml
  test/service/Cargo.toml
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1061 Fix panic in `pallet-collator-selection` benchmarking
  pallets/collator-selection/src/benchmarking.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1063 Improve conflict detection between cli flags
  client/cli/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1054 polkadot-collator: Switch to wasm only
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1065 ci: fix missing quotes
  .github/workflows/release-10_docker.yml
Labels: A2-insubstantial, B0-silent, C1-low 📌, ci

#1066 ci: add manual docker release workflow
  .github/workflows/release-10_docker-manual.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, ci

#1067 ci: use sensible keyserver for gpg key retrieval
  .github/workflows/release-10_docker-manual.yml
  .github/workflows/release-10_docker.yml
Labels: A0-pleasereview, B0-silent, C1-low 📌, ci

#949 Companion PR for storage changes
  Cargo.lock
  test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌, A7-companion

#1069 Support running relay chain full node as non-collator
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-rpc-interface/Cargo.toml
  parachain-template/node/src/service.rs
  polkadot-parachains/src/service.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1051 Companion for Substrate#10915
  Cargo.lock
  client/relay-chain-rpc-interface/src/lib.rs
Labels: B0-silent, C1-low 📌

#1070 Companion for #10896: Minor Uniques pallet improvements
  Cargo.lock
  parachain-template/runtime/src/xcm_config.rs
  polkadot-parachains/canvas-kusama/src/xcm_config.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/shell/src/lib.rs
  polkadot-parachains/shell/src/xcm_config.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemine/src/xcm_config.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/xcm_config.rs
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/xcm_config.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#982 Add benchmarks for Xcmp QueueConfigData setters
  Cargo.lock
  pallets/xcmp-queue/Cargo.toml
  pallets/xcmp-queue/src/benchmarking.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  pallets/xcmp-queue/src/weights.rs
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/canvas-kusama/src/xcm_config.rs
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/statemine/src/weights/mod.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/statemint/src/weights/mod.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/westmint/src/weights/mod.rs
  scripts/benchmarks.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1055 Use WeightToFee when calculating cost of each weight unit in XCM trader
  parachain-template/runtime/src/xcm_config.rs
  polkadot-parachains/canvas-kusama/src/xcm_config.rs
  polkadot-parachains/statemine/src/xcm_config.rs
  polkadot-parachains/statemint/src/xcm_config.rs
  polkadot-parachains/westmint/src/xcm_config.rs
Labels: A0-pleasereview, B1-releasenotes, M5-statemint, C1-low 📌

#1071 Companion for primitives consolidation into v2
  Cargo.lock
  client/collator/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/src/lib.rs
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/common/src/tests.rs
  client/consensus/relay-chain/src/lib.rs
  client/network/src/lib.rs
  client/network/src/tests.rs
  client/pov-recovery/src/lib.rs
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/lib.rs
  client/service/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/tests.rs
  pallets/solo-to-para/src/lib.rs
  pallets/xcmp-queue/Cargo.toml
  parachain-template/node/Cargo.toml
  parachain-template/node/src/command.rs
  polkadot-parachains/parachains-common/src/impls.rs
  polkadot-parachains/src/command.rs
  polkadot-parachains/src/service.rs
  primitives/core/src/lib.rs
  primitives/parachain-inherent/src/client_side.rs
  primitives/timestamp/src/lib.rs
  test/client/src/block_builder.rs
  test/relay-sproof-builder/src/lib.rs
  test/service/src/genesis.rs
  test/service/src/lib.rs
Labels: A0-pleasereview, B0-silent, Q0-trivial, C1-low 📌

#1076 Co #5064: Use runtime dependant weights
  Cargo.lock
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  polkadot-parachains/canvas-kusama/Cargo.toml
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
Labels: A3-inprogress, B0-silent, C1-low 📌, A7-companion

#1079 Make CI work
  parachain-template/runtime/Cargo.toml
  polkadot-parachains/canvas-kusama/Cargo.toml
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/westmint/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1080 Directly use the new `to_memory_db` function
  pallets/parachain-system/src/validate_block/implementation.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1081 Co #5091: Runtime dependent weights for parachains
  Cargo.lock
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  parachain-template/runtime/src/weights/block_weights.rs
  parachain-template/runtime/src/weights/extrinsic_weights.rs
  parachain-template/runtime/src/weights/mod.rs
  parachain-template/runtime/src/weights/paritydb_weights.rs
  parachain-template/runtime/src/weights/rocksdb_weights.rs
  polkadot-parachains/canvas-kusama/Cargo.toml
  polkadot-parachains/canvas-kusama/src/lib.rs
  polkadot-parachains/canvas-kusama/src/weights/block_weights.rs
  polkadot-parachains/canvas-kusama/src/weights/extrinsic_weights.rs
  polkadot-parachains/canvas-kusama/src/weights/mod.rs
  polkadot-parachains/canvas-kusama/src/weights/paritydb_weights.rs
  polkadot-parachains/canvas-kusama/src/weights/rocksdb_weights.rs
  polkadot-parachains/statemine/Cargo.toml
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemine/src/weights/block_weights.rs
  polkadot-parachains/statemine/src/weights/extrinsic_weights.rs
  polkadot-parachains/statemine/src/weights/mod.rs
  polkadot-parachains/statemine/src/weights/paritydb_weights.rs
  polkadot-parachains/statemine/src/weights/rocksdb_weights.rs
  polkadot-parachains/statemint/Cargo.toml
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/weights/block_weights.rs
  polkadot-parachains/statemint/src/weights/extrinsic_weights.rs
  polkadot-parachains/statemint/src/weights/mod.rs
  polkadot-parachains/statemint/src/weights/paritydb_weights.rs
  polkadot-parachains/statemint/src/weights/rocksdb_weights.rs
  polkadot-parachains/westmint/Cargo.toml
  polkadot-parachains/westmint/src/lib.rs
  polkadot-parachains/westmint/src/weights/block_weights.rs
  polkadot-parachains/westmint/src/weights/extrinsic_weights.rs
  polkadot-parachains/westmint/src/weights/mod.rs
  polkadot-parachains/westmint/src/weights/paritydb_weights.rs
  polkadot-parachains/westmint/src/weights/rocksdb_weights.rs
Labels: A0-pleasereview, B0-silent, F6-refactor 🧹, C1-low 📌, A7-companion

#1084 --json-file param is nicer.
  scripts/benchmarks.sh
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1093 collator-selection pallet tidy
  pallets/collator-selection/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1099 xcmp swap - express intent better
  pallets/xcmp-queue/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1103 bump versions in preparation for next release
  Cargo.lock
  polkadot-parachains/Cargo.toml
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1100 xcmp-queue / less indexing
  pallets/xcmp-queue/src/lib.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1105 bump version release
  Cargo.lock
  polkadot-parachains/Cargo.toml
  polkadot-parachains/rococo-parachain/src/lib.rs
  polkadot-parachains/seedling/src/lib.rs
  polkadot-parachains/statemine/src/lib.rs
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/westmint/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low 📌

#1057 Enable DOT-over-XCM and Lift Asset Creation Restrictions
  polkadot-parachains/statemint/src/lib.rs
  polkadot-parachains/statemint/src/xcm_config.rs
Labels: A0-pleasereview, M5-statemint, B7-runtimenoteworthy, C1-low 📌

#1089 Companion for revert command new API (#11022)
  Cargo.lock
  parachain-template/node/src/command.rs
  polkadot-parachains/src/command.rs
Labels: B0-silent, Q0-trivial, C1-low 📌

#1109 Move scripts used in CI to the new location
  .github/workflows/check-labels.yml
  .github/workflows/extrinsic-ordering-check-from-bin.yml
  .github/workflows/release-02_create-draft.yml
  CODEOWNERS
  docker/polkadot-collator_builder.Containerfile
  docker/test-parachain-collator.dockerfile
  scripts/ci/changelog/.gitignore
  scripts/ci/changelog/Gemfile
  scripts/ci/changelog/Gemfile.lock
  scripts/ci/changelog/README.md
  scripts/ci/changelog/bin/changelog
  scripts/ci/changelog/digests/.gitignore
  scripts/ci/changelog/digests/.gitkeep
  scripts/ci/changelog/lib/changelog.rb
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/changes.md.tera
  scripts/ci/changelog/templates/changes_client.md.tera
  scripts/ci/changelog/templates/changes_misc.md.tera
  scripts/ci/changelog/templates/changes_runtime.md.tera
  scripts/ci/changelog/templates/compiler.md.tera
  scripts/ci/changelog/templates/debug.md.tera
  scripts/ci/changelog/templates/docker_image.md.tera
  scripts/ci/changelog/templates/global_priority.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
  scripts/ci/changelog/templates/host_functions.md.tera
  scripts/ci/changelog/templates/migrations.md.tera
  scripts/ci/changelog/templates/pre_release.md.tera
  scripts/ci/changelog/templates/runtime.md.tera
  scripts/ci/changelog/templates/runtimes.md.tera
  scripts/ci/changelog/templates/template.md.tera
  scripts/ci/changelog/test/test_basic.rb
  scripts/ci/common/lib.sh
  scripts/ci/extrinsic-ordering-filter.sh
  scripts/ci/github/check_labels.sh
  scripts/ci/github/runtime-version.rb
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1110 Fix #851
  .github/workflows/release-02_create-draft.yml
  .gitignore
  polkadot-parachains/canvas-kusama/src/lib.rs
  scripts/ci/changelog/README.md
  scripts/ci/changelog/bin/changelog
  scripts/ci/changelog/templates/global_priority.md.tera
  scripts/ci/changelog/templates/high_priority.md.tera
  scripts/ci/changelog/templates/host_functions.md.tera
  scripts/ci/changelog/templates/migrations-db.md.tera
  scripts/ci/changelog/templates/migrations-runtime.md.tera
  scripts/ci/changelog/templates/template.md.tera
Labels: A2-insubstantial, A3-inprogress, B0-silent, C1-low 📌

#1116 Skip runtime migrations for the client release
  scripts/ci/changelog/templates/change.md.tera
  scripts/ci/changelog/templates/debug.md.tera
  scripts/ci/changelog/templates/host_functions.md.tera
  scripts/ci/changelog/templates/template.md.tera
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1120 Update weights from bm2 for v800
  polkadot-parachains/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/statemine/src/weights/frame_system.rs
  polkadot-parachains/statemine/src/weights/pallet_assets.rs
  polkadot-parachains/statemine/src/weights/pallet_balances.rs
  polkadot-parachains/statemine/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemine/src/weights/pallet_multisig.rs
  polkadot-parachains/statemine/src/weights/pallet_proxy.rs
  polkadot-parachains/statemine/src/weights/pallet_session.rs
  polkadot-parachains/statemine/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemine/src/weights/pallet_uniques.rs
  polkadot-parachains/statemine/src/weights/pallet_utility.rs
  polkadot-parachains/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/statemint/src/weights/frame_system.rs
  polkadot-parachains/statemint/src/weights/pallet_assets.rs
  polkadot-parachains/statemint/src/weights/pallet_balances.rs
  polkadot-parachains/statemint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/statemint/src/weights/pallet_multisig.rs
  polkadot-parachains/statemint/src/weights/pallet_proxy.rs
  polkadot-parachains/statemint/src/weights/pallet_session.rs
  polkadot-parachains/statemint/src/weights/pallet_timestamp.rs
  polkadot-parachains/statemint/src/weights/pallet_uniques.rs
  polkadot-parachains/statemint/src/weights/pallet_utility.rs
  polkadot-parachains/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  polkadot-parachains/westmint/src/weights/frame_system.rs
  polkadot-parachains/westmint/src/weights/pallet_assets.rs
  polkadot-parachains/westmint/src/weights/pallet_balances.rs
  polkadot-parachains/westmint/src/weights/pallet_collator_selection.rs
  polkadot-parachains/westmint/src/weights/pallet_multisig.rs
  polkadot-parachains/westmint/src/weights/pallet_proxy.rs
  polkadot-parachains/westmint/src/weights/pallet_session.rs
  polkadot-parachains/westmint/src/weights/pallet_timestamp.rs
  polkadot-parachains/westmint/src/weights/pallet_uniques.rs
  polkadot-parachains/westmint/src/weights/pallet_utility.rs
Labels: A0-pleasereview, B0-silent, C1-low 📌

#1122 Hide unwanted hashes for parachain runtimes
  scripts/ci/changelog/templates/runtime.md.tera
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌

#1125 Fix target docker hub org
  .github/workflows/release-10_docker-manual.yml
  .github/workflows/release-10_docker.yml
Labels: A2-insubstantial, A0-pleasereview, B0-silent, C1-low 📌
