Repository paritytech/cumulus, pull requests merged in 2023-05, with the labels that each got.

#2497 Skip av-store in collator overseer
  Cargo.lock
  client/relay-chain-minimal-node/src/collator_overseer.rs
  client/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, T0-node, D3-trivial 🧸

#2505 Bump clap to 4.2.5
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low, E2-dependencies

#2511 [ci] Run gha fmt in docker
  .github/workflows/fmt-check.yml
Labels: B0-silent, A0-please_review, C1-low

#2509 Update polkadot dependencies
  Cargo.lock
  client/network/src/lib.rs
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸

#2513 [Backport] Update polkadot dependencies (#2509) to source branch
  Cargo.lock
  client/network/src/lib.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2512 [Backport ]Update polkadot dependencies (#2509) to client release branch
  Cargo.lock
  client/network/src/lib.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2510 Companion PR for add events to ContractResult
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#2515 Update polkadot dependencies
  Cargo.lock
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸

#2111 BridgeHub Rococo/Wococo runtimes
  Cargo.lock
  pallets/parachain-system/src/lib.rs
  parachains/chain-specs/bridge-hub-rococo.json
  parachains/chain-specs/bridge-hub-wococo.json
  parachains/runtimes/assets/test-utils/Cargo.toml
  parachains/runtimes/assets/test-utils/src/lib.rs
  parachains/runtimes/assets/test-utils/src/test_cases.rs
  parachains/runtimes/bridge-hubs/README.md
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa_bridge_rococo_grandpa.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa_bridge_wococo_grandpa.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_bridge_messages_bench_runtime_with_bridge_hub_rococo_messages_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_bridge_messages_bench_runtime_with_bridge_hub_wococo_messages_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains_bridge_parachains_bench_runtime_bridge_parachain_rococo_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains_bridge_parachains_bench_runtime_bridge_parachain_wococo_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_relayers.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  parachains/runtimes/bridge-hubs/test-utils/src/lib.rs
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  polkadot-parachain/src/chain_spec/bridge_hubs.rs
  scripts/bridges_rococo_wococo.sh
  scripts/bridges_update_subtree.sh
  scripts/generate_hex_encoded_call/index.js
  scripts/generate_hex_encoded_call/package-lock.json
  scripts/generate_hex_encoded_call/package.json
  zombienet/bridge-hubs/bridge_hub_rococo_local_network.toml
  zombienet/bridge-hubs/bridge_hub_wococo_local_network.toml
Labels: A0-please_review, B1-note_worthy, C3-medium, T1-runtime

#2519 [Backport] Update polkadot dependencies (#2515) to the source release branch
  Cargo.lock
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2417 companion for #13384
  Cargo.lock
  client/cli/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/tests/common.rs
  test/service/src/cli.rs
  test/service/src/lib.rs
Labels: A4-companion, B1-note_worthy, C1-low, T0-node

#2423 Companion for #13701
  Cargo.lock
  parachain-template/node/src/cli.rs
  polkadot-parachain/src/cli.rs
  test/service/src/cli.rs
  test/service/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T0-node

#2502 [Feature] XCM-Emulator
  xcm/xcm-emulator/Cargo.toml
  xcm/xcm-emulator/README.md
  xcm/xcm-emulator/example/src/lib.rs
  xcm/xcm-emulator/test-runtime/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2463 Companion: XCM remote lock config
  Cargo.lock
  parachain-template/runtime/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2524 Update DNS names of Rococo Contracts bootnodes
  parachains/chain-specs/contracts-rococo.json
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2530 [Backport] Bump transaction_version (#2520) to the client release branch
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2531 [Backport] Bump transaction_version (#2520) to the source release branch
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2525 bump zombienet version
  .gitlab-ci.yml
  zombienet/tests/register-para.js
Labels: B0-silent, A0-please_review, C1-low

#2527 Make zombienet tests required
  scripts/ci/gitlab/pipeline/zombienet.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2521 Update westmint bootnodes
  parachains/chain-specs/westmint.json
Labels: B0-silent, C1-low

#2539 companion for #14088
  Cargo.lock
  test/service/src/lib.rs
Labels: B0-silent, A4-companion, C1-low

#2532 [benchmarks] Update weights for collectives
  .gitlab-ci.yml
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_preimage.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_ranked_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_referenda.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_scheduler.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_xcm.rs
  zombienet/tests/register-para.js
Labels: B0-silent, T9-release, A0-please_review, C1-low

#2537 Add `set_invulnerables` to `SafeCallFilter`
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low, D3-trivial 🧸

#2437 Substrate 13843 (Asset Freezing) Companion
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#2541 [Backport] add set_invulnerables to SafeCallFilter (#2537) to release runtimes branch
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#2546 [Backport] add set_invulnerables to SafeCallFilter (#2537) to source release branch
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2550 Collectives: xcm base weights
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, A0-please_review, T1-runtime, D3-trivial 🧸

#2553 [Backport] #2550 and substrate deps update to runtimes release
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2555 [Backport] #2550 and substrate deps update to source release
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2554 [Backport] #2550 and substrate deps update to client release
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, T9-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2514 Substrate Companion
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2551 aura-ext: limit the number of authored blocks per slot
  pallets/aura-ext/Cargo.toml
  pallets/aura-ext/src/consensus_hook.rs
  pallets/aura-ext/src/lib.rs
  pallets/parachain-system/src/consensus_hook.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/tests.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#2559 Bump parity-db
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2429 [Substrate Companion] Upgrade to libp2p 0.51.3
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low

#2561 [Backport] version bumps from 9420
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2552 Relay-parent digest logs for parachains
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  primitives/core/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2574 remove sp-serializer
  Cargo.lock
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/command.rs
Labels: A2-insubstantial, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#2221 Collectives integration tests xcm v3
  parachains/integration-tests/collectives/0_xcm/0_init.yml
  parachains/integration-tests/collectives/0_xcm/1_teleport.yml
  parachains/integration-tests/collectives/0_xcm/2_reserve.yml
  parachains/integration-tests/collectives/1_alliance/1_init_alliance.yml
  parachains/integration-tests/collectives/1_alliance/3_kick_member.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2572 BridgeHubRococo/Wococo nits + updated subtree
  Cargo.lock
  bridges/bin/runtime-common/Cargo.toml
  bridges/bin/runtime-common/src/messages.rs
  bridges/bin/runtime-common/src/messages_call_ext.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/messages/src/benchmarking.rs
  bridges/modules/messages/src/inbound_lane.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/messages/src/outbound_lane.rs
  bridges/modules/parachains/src/lib.rs
  bridges/primitives/chain-bridge-hub-kusama/src/lib.rs
  bridges/primitives/chain-bridge-hub-polkadot/src/lib.rs
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/header-chain/src/justification.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/primitives/messages/Cargo.toml
  bridges/primitives/messages/src/lib.rs
  bridges/primitives/messages/src/source_chain.rs
  bridges/primitives/messages/src/target_chain.rs
  bridges/primitives/polkadot-core/src/parachains.rs
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/runtime/src/lib.rs
  bridges/scripts/verify-pallets-build.sh
  parachain-template/runtime/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/README.md
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  scripts/bridges_rococo_wococo.sh
  zombienet/bridge-hubs/bridge_hub_rococo_local_network.toml
  zombienet/bridge-hubs/bridge_hub_wococo_local_network.toml
Labels: B0-silent, A0-please_review, C1-low, T8-bridges

#2501 refactor unincluded segment length into a ConsensusHook
  Cargo.lock
  client/collator/Cargo.toml
  client/collator/src/lib.rs
  client/consensus/common/Cargo.toml
  client/consensus/common/src/tests.rs
  pallets/aura-ext/Cargo.toml
  pallets/aura-ext/src/consensus_hook.rs
  pallets/aura-ext/src/lib.rs
  pallets/parachain-system/src/consensus_hook.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/tests.rs
  pallets/parachain-system/src/unincluded_segment.rs
  pallets/parachain-system/src/validate_block/tests.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  primitives/timestamp/src/lib.rs
  test/runtime/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, F3-breaks_API, T1-runtime

#2294 Glutton Parachain
  Cargo.lock
  Cargo.toml
  parachains/chain-specs/glutton/kusama/glutton-kusama-1300.json
  parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  parachains/runtimes/glutton/glutton-kusama/build.rs
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/src/weights/mod.rs
  parachains/runtimes/glutton/glutton-kusama/src/weights/pallet_glutton.rs
  parachains/runtimes/glutton/glutton-kusama/src/xcm_config.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/chain_spec/glutton.rs
  polkadot-parachain/src/chain_spec/mod.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
  scripts/benchmarks-ci.sh
  scripts/benchmarks.sh
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low, D3-trivial 🧸

#2589 Bump polkadot
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low

#2557 Added Dwellir bootnodes.
  parachains/chain-specs/bridge-hub-kusama.json
  parachains/chain-specs/bridge-hub-polkadot.json
  parachains/chain-specs/bridge-hub-westend.json
  parachains/chain-specs/collectives-polkadot.json
  parachains/chain-specs/collectives-westend.json
  parachains/chain-specs/statemine.json
  parachains/chain-specs/statemint.json
  parachains/chain-specs/westmint.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2602 Bump bridges
  bridges/Cargo.lock
  bridges/README.md
  bridges/bin/runtime-common/src/messages_benchmarking.rs
  bridges/bin/runtime-common/src/parachains_benchmarking.rs
  bridges/modules/messages/src/benchmarking.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/parachains/src/mock.rs
  bridges/modules/relayers/src/benchmarking.rs
Labels: B0-silent, A0-please_review, C1-low

#2603 Update README.md
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2605 Co #14171: Update syn
  Cargo.lock
Labels: A2-insubstantial, B0-silent, A4-companion, C1-low, D3-trivial 🧸

#2608 Switch to `relay_dispatch_queue_remaining_capacity`
  Cargo.lock
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/tests.rs
  parachains/integration-tests/emulated/common/src/lib.rs
  primitives/parachain-inherent/src/client_side.rs
  test/relay-sproof-builder/src/lib.rs
  xcm/xcm-emulator/Cargo.toml
  xcm/xcm-emulator/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2599 companion for substrate#13800
  test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2611 Chainspecs: Fix bootnode address
  parachains/chain-specs/bridge-hub-kusama.json
  parachains/chain-specs/bridge-hub-polkadot.json
  parachains/chain-specs/bridge-hub-westend.json
  parachains/chain-specs/collectives-polkadot.json
  parachains/chain-specs/collectives-westend.json
  parachains/chain-specs/statemine.json
  parachains/chain-specs/statemint.json
  parachains/chain-specs/westmint.json
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2613 Update substrate/polkadot + needed changes to compile
  Cargo.lock
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2594 parachain-system: ignore go ahead signal once upgrade is processed
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/parachain-system/src/unincluded_segment.rs
Labels: B0-silent, A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#2595 NFTs 2.0 on Statemint
  Cargo.lock
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/weights/mod.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_nfts.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2615 Try-runtime proper return types
  Cargo.lock
  parachains/runtimes/collectives/collectives-polkadot/src/fellowship/migration.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2600 NFT Fractionalization on Westmint
  Cargo.lock
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/weights/mod.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_nft_fractionalization.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2586 Do not assume `AssetId`s are `Copy` (companion for substrate#14158)
  Cargo.lock
  parachains/common/src/impls.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  primitives/utility/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, I7-refactor, D3-trivial 🧸

#2616 Use default for intergration test relay runtimes
  parachains/integration-tests/emulated/common/src/constants.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2612 Companion for substrate#14188 (Add genesis config to Glutton pallet)
  Cargo.lock
  parachains/chain-specs/glutton/kusama/glutton-kusama-1300.json
  parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  polkadot-parachain/src/chain_spec/glutton.rs
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low, J0-enhancement, D3-trivial 🧸

#2540 Add Foreign Assets to Statemint
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/statemint/tests/tests.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D1-audited 👍, T1-runtime

#2627 Change SA for Rococo/Statemine_1000 + removed `CheckedExtrinsic`
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  scripts/bridges_rococo_wococo.sh
  scripts/generate_hex_encoded_call/index.js
Labels: B0-silent, A0-please_review, C1-low

#2623 Companion for #14178: Update cargo.lock to point to substrate
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2629 Updated README.md for bridges
  BRIDGES.md
  parachains/runtimes/bridge-hubs/README.md
Labels: B0-silent, A0-please_review, C1-low

#2630 add statemine emulator tests
  Cargo.lock
  Cargo.toml
  parachains/integration-tests/emulated/assets/statemine/Cargo.toml
  parachains/integration-tests/emulated/assets/statemine/src/lib.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/transact.rs
  parachains/integration-tests/emulated/common/src/constants.rs
  parachains/integration-tests/emulated/common/src/lib.rs
  xcm/xcm-emulator/README.md
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2614 Update & revamp e2e tests
  client/network/src/lib.rs
  parachains/integration-tests/e2e/assets/statemine/0_xcm/0_init.yml
  parachains/integration-tests/e2e/assets/statemine/0_xcm/1_dmp.yml
  parachains/integration-tests/e2e/assets/statemine/0_xcm/2_ump.yml
  parachains/integration-tests/e2e/assets/statemine/0_xcm/3_force_hrmp-open-channels.yml
  parachains/integration-tests/e2e/assets/statemine/0_xcm/4_hrmp.yml
  parachains/integration-tests/e2e/assets/statemine/config.toml
  parachains/integration-tests/e2e/assets/statemint/0_xcm/0_init.yml
  parachains/integration-tests/e2e/assets/statemint/0_xcm/1_dmp.yml
  parachains/integration-tests/e2e/assets/statemint/0_xcm/2_ump.yml
  parachains/integration-tests/e2e/assets/statemint/0_xcm/3_force_hrmp-open-channels.yml
  parachains/integration-tests/e2e/assets/statemint/0_xcm/4_hrmp.yml
  parachains/integration-tests/e2e/assets/statemint/config.toml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/0_init.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/1_teleport.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/2_reserve.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/0_join_alliance_fails.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/1_init_alliance.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/2_join_alliance_fails.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/3_kick_member.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/config.toml
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low, D3-trivial 🧸

#2631 Companion for: Substrate#13869
  Cargo.lock
  bridges/bin/runtime-common/src/mock.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/relayers/src/mock.rs
  pallets/collator-selection/src/mock.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/runtime/src/lib.rs
  parachains/common/src/impls.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2635 Fix typo in test
  parachains/integration-tests/emulated/assets/statemint/src/tests/teleport.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2637 bump zombienet version
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#2640 bump substrate version
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2601 Companion for polkadot#7234 (XCM: Tools for uniquely referencing messages)
  Cargo.lock
  Cargo.toml
  pallets/dmp-queue/src/lib.rs
  pallets/xcmp-queue/src/lib.rs
  parachain-template/runtime/src/xcm_config.rs
  parachains/common/src/xcm_config.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/teleport.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
  parachains/runtimes/test-utils/src/lib.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  primitives/utility/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D9-needsaudit 👮, T1-runtime

#2621 Companion for Polkadot 7253
  Cargo.lock
  test/relay-validation-worker-provider/Cargo.toml
  test/relay-validation-worker-provider/build.rs
  test/relay-validation-worker-provider/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2624 pallets: implement `Default` for `GenesisConfig` in `no_std`
  Cargo.lock
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/parachains/src/lib.rs
  pallets/collator-selection/src/lib.rs
  parachains/pallets/parachain-info/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2160 polkompanion 6667: past session slashing
  Cargo.lock
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, T3-relay_chain, T1-runtime, D3-trivial 🧸

#2638 Glutton script chain spec generator
  polkadot-parachain/src/chain_spec/glutton.rs
  scripts/create_glutton_spec.sh
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low

#2643 Companion for #14237: Use latest sp-crates
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2596 Add Ability to Add/Remove Invulnerable Collators
  pallets/collator-selection/Cargo.toml
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/migration.rs
  pallets/collator-selection/src/mock.rs
  pallets/collator-selection/src/tests.rs
  pallets/collator-selection/src/weights.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#2656 Add correct Sign Extensions to Glutton parachain
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low

#2662 Update polkadot dependencies in runtimes release branch
  Cargo.lock
  client/network/src/lib.rs
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸
