Repository paritytech/cumulus, pull requests merged in 2023-01, with the labels that each got.

#2047 remove shift session manager from bridge-hub-rococo
  Cargo.lock
  Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D2-notlive 💤

#2041 BlockId removal: refactor: BlockBackend::block|block_status
  Cargo.lock
  client/collator/src/lib.rs
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/common/src/tests.rs
  client/pov-recovery/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2039 Backport: remove 9330 migrations from statemint series (#2031) to master
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2037 Backport version bumps from 9360
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2057 Co #6498: Selectable on-runtime-upgrade checks
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2056 upgrade libp2p to 0.50.0
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2058 NFTs 2.0 on Westmint
  Cargo.lock
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/weights/mod.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_nfts.rs
Labels: A0-please_review, B1-note_worthy, C3-medium, D5-nicetohaveaudit ⚠️, T1-runtime

#2068 Remove the `RelaychainClient` trait
  Cargo.lock
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/common/src/tests.rs
  client/network/Cargo.toml
  client/network/src/tests.rs
  client/relay-chain-interface/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2067 Use primitives reexported from `polkadot_primitives` crate root
  Cargo.lock
  client/collator/src/lib.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/src/lib.rs
  client/consensus/common/src/parachain_consensus.rs
  client/consensus/relay-chain/src/lib.rs
  client/network/src/lib.rs
  client/network/src/tests.rs
  client/pov-recovery/src/lib.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  client/relay-chain-minimal-node/src/collator_overseer.rs
  client/relay-chain-minimal-node/src/lib.rs
  client/relay-chain-rpc-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
  client/service/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/tests.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/parachain-system/src/validate_block/mod.rs
  pallets/solo-to-para/src/lib.rs
  parachain-template/node/src/command.rs
  parachain-template/runtime/src/lib.rs
  parachains/common/src/impls.rs
  parachains/common/src/lib.rs
  parachains/common/src/xcm_config.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/penpal/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
  primitives/core/src/lib.rs
  primitives/parachain-inherent/src/client_side.rs
  primitives/timestamp/src/lib.rs
  test/client/src/block_builder.rs
  test/relay-sproof-builder/src/lib.rs
  test/runtime/src/lib.rs
  test/service/src/genesis.rs
  test/service/src/lib.rs
  test/service/src/main.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2077 Remove update-parachain-template
  scripts/ci/gitlab/pipeline/publish.yml
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#2078 Minor update to Readme - Statemint section
  README.md
  parachains/README.md
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2086 update polkadot dependencies
  Cargo.lock
Labels: B0-silent, T10-release, A0-please_review, C1-low, D3-trivial 🧸

#2089 [Backport] of update polkadot dependencies (#2086)
  Cargo.lock
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2088 [Backport] of update polkadot dependecies (#2086)
  Cargo.lock
Labels: B0-silent, T10-release, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2093 [benchmarks] pr with weights Bridge-hub
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low

#2092 [benchmarks] pr with weights Statemint/e
  parachains/runtimes/assets/statemine/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemine/src/weights/frame_system.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemine/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/statemint/src/weights/frame_system.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_session.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/statemint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/westmint/src/weights/frame_system.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_balances.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_session.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/westmint/src/weights/pallet_utility.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low

#2094 [benchmarks] pr with weights Collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
Labels: B0-silent, A0-please_review, C1-low

#2103 Remove 9360 migrations
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2104 [backport] remove collectives migrations (#2103) from runtime release branch
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#2105 [backport] remove 9360 collectives migrations (#2103)
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#1908 Instantiate All Assets Pallets
  parachains/common/src/impls.rs
  parachains/common/src/lib.rs
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/src/xcm_config.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/src/xcm_config.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2108 Companion for substrate#12993
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#2112 Companion for paritytech/polkadot#6578
  Cargo.lock
  parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
  parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#2095 [backport] version bumps from release 9370
  Cargo.lock
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, A6-backport, C1-low

#2072 Simplify the template
  parachain-template/node/src/chain_spec.rs
  parachain-template/runtime/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2116 Use correct runtime function name
  client/relay-chain-rpc-interface/src/rpc_client.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#1863 Warn validators with slow hardware
  Cargo.lock
  parachain-template/node/src/command.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2128 [ci] Update check-labels and fix check
  .github/workflows/check-D-labels.yml
  .github/workflows/check-labels.yml
Labels: B0-silent, A0-please_review, C1-low

#2124 Removed forgotten unused `pub Ancestry: MultiLocation`
  parachains/runtimes/assets/westmint/src/xcm_config.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2132 Bump parity-db
  Cargo.lock
Labels: A2-insubstantial, B0-silent, C1-low

#2091 Remove assumption that there is a local bootnode in RPC collator
  .gitlab-ci.yml
  client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
  client/relay-chain-minimal-node/src/lib.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
  zombienet/tests/0006-rpc_collator_builds_blocks.toml
Labels: B0-silent, A0-please_review, C1-low

#2131 Westend Collectives raw chain spec
  parachains/chain-specs/collectives-westend.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2107 Bridge benchmarks for bridge hub rococo/wococo
  Cargo.lock
  bridges/bin/runtime-common/Cargo.toml
  bridges/bin/runtime-common/src/messages_benchmarking.rs
  bridges/modules/parachains/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa_bridge_rococo_grandpa.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa_bridge_wococo_grandpa.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_bridge_messages_bench_runtime_with_bridge_hub_rococo_messages_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_bridge_messages_bench_runtime_with_bridge_hub_wococo_messages_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains_bridge_parachains_bench_runtime_bridge_parachain_rococo_instance.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains_bridge_parachains_bench_runtime_bridge_parachain_wococo_instance.rs
  scripts/benchmarks-ci.sh
Labels: B0-silent, A0-please_review, C1-low, D2-notlive 💤, T8-bridges

#2140 Do not verify on state import for relay chain verifier
  client/consensus/relay-chain/src/import_queue.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2135 nix upgrade to 0.26.1
  Cargo.lock
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2073 13110 Companion: Add WeightToFee and LengthToFee Runtime API
  Cargo.lock
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2126 Companion: Remove `uncles` related code
  Cargo.lock
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  parachain-template/runtime/src/lib.rs
  parachains/common/src/impls.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2122 Update benchmark's successful origin api
  Cargo.lock
  pallets/collator-selection/src/benchmarking.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸
