Repository paritytech/cumulus, pull requests merged in 2023-07, with the labels that each got.

#2800 Fix for `xcm-emulator` - Wrong Parachain processing message
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low

#2805 Use 2021 edition
  bridges/primitives/parachains/Cargo.toml
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2808 Fix Unused Variable for PoolAssets Benchmark
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#2809 Backport `xcm-emulator` fixes #2800 and #2711
  parachains/integration-tests/emulated/assets/statemine/src/lib.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/transact.rs
  parachains/integration-tests/emulated/assets/statemint/src/lib.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/transact.rs
  parachains/integration-tests/emulated/collectives/collectives-polkadot/src/tests/fellowship.rs
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low

#2810 Backport `xcm-emulator` fixes #2800 and #2711
  parachains/integration-tests/emulated/assets/statemine/src/lib.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/statemine/src/tests/transact.rs
  parachains/integration-tests/emulated/assets/statemint/src/lib.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/statemint/src/tests/transact.rs
  parachains/integration-tests/emulated/collectives/collectives-polkadot/src/tests/fellowship.rs
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, T7-system_parachains, A0-please_review, C1-low

#2751 Add migration for substrate#14084
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, T4-smart_contracts, D3-trivial 🧸

#2798 [xcm] BridgeBlobDispatcher - prepend bridge instance discriminator.
  Cargo.lock
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
Labels: B0-silent, A0-please_review, C1-low

#2658 aura-ext: check slot in consensus hook and remove all `CheckInherents` logic
  Cargo.lock
  Cargo.toml
  pallets/aura-ext/Cargo.toml
  pallets/aura-ext/src/consensus_hook.rs
  pallets/aura-ext/src/lib.rs
  pallets/parachain-system/proc-macro/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/parachain-system/src/validate_block/tests.rs
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  parachains/integration-tests/emulated/common/src/lib.rs
  parachains/runtimes/assets/statemine/Cargo.toml
  parachains/runtimes/assets/statemine/src/constants.rs
  parachains/runtimes/assets/statemine/src/lib.rs
  parachains/runtimes/assets/statemine/tests/tests.rs
  parachains/runtimes/assets/statemint/Cargo.toml
  parachains/runtimes/assets/statemint/src/constants.rs
  parachains/runtimes/assets/statemint/src/lib.rs
  parachains/runtimes/assets/statemint/tests/tests.rs
  parachains/runtimes/assets/test-utils/src/test_cases.rs
  parachains/runtimes/assets/westmint/Cargo.toml
  parachains/runtimes/assets/westmint/src/constants.rs
  parachains/runtimes/assets/westmint/src/lib.rs
  parachains/runtimes/assets/westmint/tests/tests.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/tests/tests.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/tests/tests.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/src/constants.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/constants.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/test-utils/src/lib.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/Cargo.toml
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  primitives/timestamp/Cargo.toml
  primitives/timestamp/src/lib.rs
  test/runtime/Cargo.toml
  test/runtime/src/lib.rs
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, A3-in_progress, C1-low, D5-nicetohaveaudit ⚠️

#2794 introduce a method for fetching relay chain header to `RelayChainInterface`
  client/consensus/common/src/tests.rs
  client/network/src/tests.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2785 [WIP do not merge yet]: Change names of the assets to new, to fix release notes
  .github/ISSUE_TEMPLATE/release-runtime.md
  scripts/ci/changelog/bin/changelog
  scripts/ci/changelog/templates/runtime.md.tera
  scripts/ci/changelog/templates/runtimes.md.tera
Labels: B0-silent, A0-please_review, C1-low

#2820 BridgeHub subtree update
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/parachains/src/lib.rs
  bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
  bridges/primitives/header-chain/Cargo.toml
  bridges/primitives/messages/Cargo.toml
  bridges/primitives/parachains/Cargo.toml
  bridges/primitives/polkadot-core/Cargo.toml
  bridges/primitives/relayers/Cargo.toml
  bridges/primitives/runtime/Cargo.toml
  scripts/bridges_update_subtree.sh
Labels: B0-silent, A0-please_review, C1-low

#2807 Companion for Polkadot#7451
  Cargo.lock
  client/network/Cargo.toml
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-inprocess-interface/src/lib.rs
  polkadot-parachain/tests/polkadot_argument_parsing.rs
  polkadot-parachain/tests/polkadot_mdns_issue.rs
  polkadot-parachain/tests/purge_chain_works.rs
  polkadot-parachain/tests/running_the_node_and_interrupt.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2821 Companion for Substrate#14511
  Cargo.lock
  client/cli/Cargo.toml
  client/cli/src/lib.rs
  client/relay-chain-inprocess-interface/Cargo.toml
  parachain-template/node/src/command.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/chain_spec/bridge_hubs.rs
  polkadot-parachain/src/command.rs
  polkadot-parachain/src/service.rs
  test/service/src/cli.rs
  test/service/src/main.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T0-node

#2769 NFT Fractionalization on AssetHub Kusama
  Cargo.lock
  parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/mod.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_nft_fractionalization.rs
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2830 don't wrap errors in `RelayChainInterface`
  client/network/src/tests.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low

#2839 Add New Assets Privileged Functions to Appropriate Proxy Types
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#2801 Better Handling of Candidates Who Become Invulnerable
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  pallets/collator-selection/src/tests.rs
  pallets/collator-selection/src/weights.rs
  parachain-template/runtime/src/lib.rs
  parachains/common/src/impls.rs
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#2772 CollationGenerationConfig closure is now optional
  Cargo.lock
  client/collator/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, T0-node, D3-trivial 🧸

#2852 Better scoped fallback in read_messaging_state_snapshot()
  client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, E4-node_first_update

#2573 Asynchronous-backing compatible Aura, not plugged in
  Cargo.lock
  Cargo.toml
  client/collator/src/service.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/collator.rs
  client/consensus/aura/src/collators/basic.rs
  client/consensus/aura/src/collators/lookahead.rs
  client/consensus/aura/src/collators/mod.rs
  client/consensus/aura/src/equivocation_import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/aura/src/unstable_reimpl.rs
  client/consensus/common/Cargo.toml
  client/consensus/common/src/lib.rs
  client/consensus/common/src/tests.rs
  client/network/src/lib.rs
  client/network/src/tests.rs
  client/relay-chain-interface/src/lib.rs
  client/service/src/lib.rs
  primitives/aura/Cargo.toml
  primitives/aura/src/lib.rs
Labels: B0-silent, C1-low, T1-runtime, D3-trivial 🧸

#2851 collator-selection: Optimize length decoding
  pallets/collator-selection/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2853 Bump substrate (because of failing asset-hub-westend benchmarks)
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low

#2836 Companion for removal of execution strategies
  Cargo.lock
  Cargo.toml
  client/consensus/aura/src/equivocation_import_queue.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  pallets/parachain-system/src/validate_block/tests.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/service.rs
  test/service/benches/validate_block.rs
  test/service/benches/validate_block_glutton.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2857 Removed `--execution wasm`
  README.md
  scripts/benchmarks-ci.sh
Labels: B0-silent, A0-please_review, C1-low

#2757 `GenesisBuild<T,I>` deprecated. `BuildGenesisConfig` added
  Cargo.lock
  bridges/bin/runtime-common/src/mock.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/parachains/src/lib.rs
  bridges/modules/parachains/src/mock.rs
  bridges/modules/relayers/src/mock.rs
  pallets/aura-ext/src/lib.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  pallets/collator-selection/src/tests.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/node/src/chain_spec.rs
  parachain-template/pallets/template/src/mock.rs
  parachains/common/src/impls.rs
  parachains/integration-tests/emulated/common/src/constants.rs
  parachains/pallets/parachain-info/Cargo.toml
  parachains/pallets/parachain-info/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/fellowship/migration.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/test-utils/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/src/chain_spec/asset_hubs.rs
  polkadot-parachain/src/chain_spec/bridge_hubs.rs
  polkadot-parachain/src/chain_spec/collectives.rs
  polkadot-parachain/src/chain_spec/contracts.rs
  polkadot-parachain/src/chain_spec/glutton.rs
  polkadot-parachain/src/chain_spec/penpal.rs
  polkadot-parachain/src/chain_spec/rococo_parachain.rs
  polkadot-parachain/src/chain_spec/seedling.rs
  polkadot-parachain/src/chain_spec/shell.rs
  test/service/src/chain_spec.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2790 Moves `Block` to `frame_system` instead of `construct_runtime` and removes `Header` and `BlockNumber`
  Cargo.lock
  bridges/bin/runtime-common/src/integrity.rs
  bridges/bin/runtime-common/src/mock.rs
  bridges/bin/runtime-common/src/parachains_benchmarking.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/src/call_ext.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/parachains/src/benchmarking.rs
  bridges/modules/parachains/src/lib.rs
  bridges/modules/parachains/src/mock.rs
  bridges/modules/relayers/src/lib.rs
  bridges/modules/relayers/src/mock.rs
  bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
  bridges/primitives/chain-bridge-hub-kusama/src/lib.rs
  bridges/primitives/chain-bridge-hub-polkadot/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-wococo/src/lib.rs
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/chain-wococo/src/lib.rs
  bridges/primitives/header-chain/src/justification.rs
  bridges/primitives/polkadot-core/src/lib.rs
  bridges/primitives/runtime/src/chain.rs
  pallets/collator-selection/src/benchmarking.rs
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/mock.rs
  pallets/dmp-queue/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/xcmp-queue/src/lib.rs
  pallets/xcmp-queue/src/mock.rs
  parachain-template/pallets/template/src/mock.rs
  parachain-template/runtime/src/lib.rs
  parachains/common/src/impls.rs
  parachains/pallets/ping/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/tests/tests.rs
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/starters/shell/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  test/runtime/src/lib.rs
Labels: A4-companion, B1-note_worthy, C3-medium, F3-breaks_API, T1-runtime

#2869 Fix release notes generation source
  scripts/ci/changelog/bin/changelog
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸

#2870 Fix release notes generation runtimes
  scripts/ci/changelog/bin/changelog
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸

#2868 Fix release notes generation node
  scripts/ci/changelog/bin/changelog
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸

#2856 Update collectives-westend bootnodes
  parachains/chain-specs/collectives-westend.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2878 Update substrate dependencies node
  Cargo.lock
Labels: B0-silent, T9-release, A0-please_review, C1-low, D3-trivial 🧸

#2890 Move `CI_IMAGE` to external snippet via !reference
  .gitlab-ci.yml
Labels: B0-silent, A0-please_review, C1-low

#2893 Xcm-Emulator: use `ext_wrapper` to execute with externalities
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2813 Use trie-cache for `validate_block`
  Cargo.lock
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/validate_block/implementation.rs
  pallets/parachain-system/src/validate_block/mod.rs
  pallets/parachain-system/src/validate_block/trie_cache.rs
Labels: B0-silent, A0-please_review, C1-low

#2903 Update bridges subtree
  bridges/bin/runtime-common/src/integrity.rs
  bridges/bin/runtime-common/src/mock.rs
  bridges/bin/runtime-common/src/parachains_benchmarking.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/src/call_ext.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/grandpa/src/mock.rs
  bridges/modules/parachains/src/benchmarking.rs
  bridges/modules/parachains/src/lib.rs
  bridges/modules/parachains/src/mock.rs
  bridges/modules/relayers/src/mock.rs
  bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
  bridges/primitives/chain-bridge-hub-kusama/src/lib.rs
  bridges/primitives/chain-bridge-hub-polkadot/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-wococo/src/lib.rs
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/chain-wococo/src/lib.rs
  bridges/primitives/header-chain/src/justification.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/primitives/header-chain/tests/implementation_match.rs
  bridges/primitives/header-chain/tests/justification.rs
  bridges/primitives/messages/src/lib.rs
  bridges/primitives/polkadot-core/src/lib.rs
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/runtime/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#2899 propagate network-protocol-staging feature from parachain-template
  Cargo.lock
  client/relay-chain-inprocess-interface/Cargo.toml
  client/relay-chain-minimal-node/Cargo.toml
  client/service/Cargo.toml
  parachain-template/node/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2904 Use `benchmarking::v2` in collator selection pallet
  pallets/collator-selection/src/benchmarking.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2911 Feature Flagging Consensus Hook Type Parameter
  client/consensus/common/src/tests.rs
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  parachain-template/runtime/Cargo.toml
  parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  parachains/runtimes/assets/asset-hub-polkadot/Cargo.toml
  parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  parachains/runtimes/assets/test-utils/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/test-utils/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  parachains/runtimes/starters/seedling/Cargo.toml
  parachains/runtimes/starters/shell/Cargo.toml
  parachains/runtimes/test-utils/Cargo.toml
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/rococo-parachain/Cargo.toml
  test/relay-sproof-builder/src/lib.rs
  test/runtime/Cargo.toml
  test/service/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2860 Asset conversion nits
  Cargo.lock
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/Cargo.toml
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/swap.rs
  parachains/integration-tests/emulated/common/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/mod.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_asset_conversion.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  parachains/runtimes/assets/common/Cargo.toml
  parachains/runtimes/assets/common/src/fungible_conversion.rs
  parachains/runtimes/assets/common/src/local_and_foreign_assets.rs
  parachains/runtimes/assets/test-utils/src/test_cases.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/bridge-hubs/test-utils/src/test_cases.rs
  parachains/runtimes/test-utils/src/lib.rs
  parachains/runtimes/test-utils/src/test_cases.rs
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#2846 Run all benchmarks "as tests" in short setup on every PR
  .gitlab-ci.yml
  scripts/ci/gitlab/pipeline/build.yml
  scripts/ci/gitlab/pipeline/short-benchmarks.yml
Labels: B0-silent, A0-please_review, C1-low

#2926 Fix PR name
  scripts/ci/gitlab/pipeline/benchmarks.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2916 [benchmarks] Update weights for collectives
  parachains/runtimes/collectives/collectives-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_core_fellowship.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_preimage.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_ranked_collective.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_referenda.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_salary.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_scheduler.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs
  parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_xcm.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2918 [benchmarks] Update weights for asset-hub-kusama/t
  parachains/runtimes/assets/asset-hub-kusama/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/frame_system.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_assets.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_balances.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_nft_fractionalization.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_nfts.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_session.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_utility.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_xcm.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/frame_system.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_assets.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_nfts.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_utility.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/pallet_xcm.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/frame_system.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_balances.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_collator_selection.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_multisig.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_nft_fractionalization.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_nfts.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_proxy.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_session.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_timestamp.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_uniques.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_utility.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/pallet_xcm.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2917 [benchmarks] Update weights for bridge-hubs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/pallet_xcm.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/pallet_xcm.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/cumulus_pallet_xcmp_queue.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/frame_system.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_balances.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_grandpa.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_parachains.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_relayers.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_collator_selection.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_multisig.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_session.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_timestamp.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_utility.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_xcm.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2754 BHs readme nits
  parachains/integration-tests/emulated/common/src/constants.rs
  parachains/runtimes/bridge-hubs/README.md
  zombienet/bridge-hubs/bridge_hub_rococo_local_network.toml
  zombienet/bridge-hubs/bridge_hub_wococo_local_network.toml
Labels: B0-silent, A0-please_review, C1-low

#2925 improve deps for xcm-emulator
  Cargo.lock
  xcm/xcm-emulator/Cargo.toml
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#2783 Add information about the parity container image
  README.md
  docs/container.md
Labels: B0-silent, A0-please_review, C1-low

#2828 change HashFor to HashingFor
  Cargo.lock
  client/collator/src/service.rs
  client/consensus/aura/src/collator.rs
  pallets/parachain-system/src/relay_state_snapshot.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  polkadot-parachain/src/rpc.rs
  test/relay-sproof-builder/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2934 [xcm ] Compatibility fix for xcm benchmarks
  parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/mod.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/mod.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/mod.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/assets/asset-hub-westend/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Labels: B0-silent, A0-please_review, C1-low

#2941 Companion for substrate 14647
  Cargo.lock
  client/consensus/aura/src/collator.rs
  client/consensus/aura/src/collators/basic.rs
  client/consensus/aura/src/collators/lookahead.rs
  client/consensus/aura/src/equivocation_import_queue.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2937 Change Matrix to new secrets and V2 server
  .github/workflows/release-10_rc-automation.yml
  .github/workflows/release-30_create-draft.yml
  .github/workflows/release-99_bot-announce.yml
Labels: B0-silent, A0-please_review, C1-low

#2949 Explicitly set `full-node` feature for emulated tests
  parachains/integration-tests/emulated/common/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low

#2843 Add missing workspace members
  Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸
