Repository paritytech/cumulus, pull requests merged in 2023-08, with the labels that each got.

#2929 Companion for Polkadot#7337
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
Labels: A0-please_review, A4-companion, B1-note_worthy, C5-high, T0-node, D3-trivial 🧸

#2944 e2e tests for Gov2
  parachains/integration-tests/e2e/collectives/README.md
  parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/0_init.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/1_teleport.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/3_hrmp-open-channels.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/1_init_alliance.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/3_kick_member.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/2_opengov/0_assethub.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/3_fellowship/0_init.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/3_fellowship/1_whitelist_call.yml
  parachains/integration-tests/e2e/collectives/collectives-polkadot/3_fellowship/2_assethub.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2956 Companion for Polkadot#7563
  Cargo.lock
  parachains/runtimes/assets/asset-hub-kusama/tests/tests.rs
  parachains/runtimes/assets/asset-hub-polkadot/tests/tests.rs
  parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
  primitives/utility/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2948 parachain-system: update RelevantMessagingState according to the unincluded segment
  pallets/parachain-system/Cargo.toml
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/tests.rs
  pallets/parachain-system/src/unincluded_segment.rs
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D5-nicetohaveaudit ⚠️, T1-runtime

#2914 Remove collators from bootnodes list
  parachains/chain-specs/bridge-hub-kusama.json
  parachains/chain-specs/collectives-polkadot.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2864 Integrate new Aura / Parachain Consensus Logic in Parachain-Template / Polkadot-Parachain
  Cargo.lock
  client/collator/src/lib.rs
  client/consensus/aura/Cargo.toml
  client/consensus/aura/src/collator.rs
  client/consensus/aura/src/collators/basic.rs
  client/consensus/aura/src/collators/lookahead.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/src/lib.rs
  client/consensus/common/src/tests.rs
  client/service/src/lib.rs
  pallets/aura-ext/src/consensus_hook.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/unincluded_segment.rs
  parachain-template/node/Cargo.toml
  parachain-template/node/src/service.rs
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/constants.rs
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/constants.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/constants.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/constants.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/constants.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/constants.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/service.rs
  test/service/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D5-nicetohaveaudit ⚠️, T0-node

#2977 (async backing) restore `CheckInherents` for backwards-compatibility
  Cargo.lock
  Cargo.toml
  pallets/parachain-system/proc-macro/src/lib.rs
  pallets/parachain-system/src/lib.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  primitives/timestamp/Cargo.toml
  primitives/timestamp/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2982 update weight file template
  templates/xcm-bench-template.hbs
Labels: B0-silent, A0-please_review, C1-low

#2642 Polkadot parachains get topic-based message IDs
  parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: A0-please_review, B1-note_worthy, C1-low, D1-audited 👍, T1-runtime

#2991 Bridges subtree sync
  Cargo.lock
  bridges/bin/runtime-common/src/messages.rs
  bridges/bin/runtime-common/src/messages_xcm_extension.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/grandpa/src/storage_types.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/parachains/src/lib.rs
  bridges/primitives/chain-bridge-hub-kusama/src/lib.rs
  bridges/primitives/chain-bridge-hub-polkadot/src/lib.rs
  bridges/primitives/chain-bridge-hub-rococo/src/lib.rs
  bridges/primitives/chain-bridge-hub-wococo/src/lib.rs
  bridges/primitives/chain-kusama/Cargo.toml
  bridges/primitives/chain-kusama/src/lib.rs
  bridges/primitives/chain-polkadot/Cargo.toml
  bridges/primitives/chain-polkadot/src/lib.rs
  bridges/primitives/chain-rococo/Cargo.toml
  bridges/primitives/chain-rococo/src/lib.rs
  bridges/primitives/chain-wococo/Cargo.toml
  bridges/primitives/chain-wococo/src/lib.rs
  bridges/primitives/header-chain/src/justification.rs
  bridges/primitives/header-chain/src/justification/mod.rs
  bridges/primitives/header-chain/src/justification/verification/equivocation.rs
  bridges/primitives/header-chain/src/justification/verification/mod.rs
  bridges/primitives/header-chain/src/justification/verification/optimizer.rs
  bridges/primitives/header-chain/src/justification/verification/strict.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/primitives/header-chain/tests/implementation_match.rs
  bridges/primitives/header-chain/tests/justification/equivocation.rs
  bridges/primitives/header-chain/tests/justification/optimizer.rs
  bridges/primitives/header-chain/tests/justification/strict.rs
  bridges/primitives/header-chain/tests/tests.rs
  bridges/primitives/messages/src/source_chain.rs
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/runtime/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low

#2958 Replicate `e2e` integration test as `emulated`
  Cargo.lock
  parachains/integration-tests/emulated/assets/asset-hub-kusama/Cargo.toml
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/lib.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/hrmp_channels.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/send.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/set_xcm_versions.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/transact.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/Cargo.toml
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/lib.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/hrmp_channels.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/send.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/set_xcm_versions.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/transact.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/Cargo.toml
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/lib.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/reserve_transfer.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/send.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/set_xcm_versions.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/swap.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/transact.rs
  parachains/integration-tests/emulated/bridges/bridge-hub-rococo/Cargo.toml
  parachains/integration-tests/emulated/bridges/bridge-hub-rococo/src/lib.rs
  parachains/integration-tests/emulated/bridges/bridge-hub-rococo/src/tests/example.rs
  parachains/integration-tests/emulated/collectives/collectives-polkadot/Cargo.toml
  parachains/integration-tests/emulated/collectives/collectives-polkadot/src/lib.rs
  parachains/integration-tests/emulated/collectives/collectives-polkadot/src/tests/fellowship.rs
  parachains/integration-tests/emulated/common/Cargo.toml
  parachains/integration-tests/emulated/common/src/constants.rs
  parachains/integration-tests/emulated/common/src/impls.rs
  parachains/integration-tests/emulated/common/src/lib.rs
  xcm/xcm-emulator/Cargo.toml
  xcm/xcm-emulator/src/lib.rs
Labels: B0-silent, T7-system_parachains, A0-please_review

#2992 fix failing gha because of the wrong assignee
  .github/workflows/release-10_rc-automation.yml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2996 companion for 14754: cli: move no-beefy flag to sc-cli
  Cargo.lock
  client/cli/src/lib.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  test/service/src/cli.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low

#2993 add metaspan boot nodes
  parachains/chain-specs/bridge-hub-polkadot.json
  parachains/chain-specs/bridge-hub-westend.json
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#3002 Combine `NativeAsset` into `ConcreteNativeAssetFromSystem`
  parachains/common/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
  parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
Labels: B0-silent, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#2989 add test-utils feature to polkadot-node-core-pvf
  Cargo.lock
  test/relay-validation-worker-provider/Cargo.toml
Labels: B0-silent, A0-please_review, A4-companion, C1-low, D3-trivial 🧸

#3012 XcmpQueue simplify - `PriceForSiblingDelivery` replaced by `runtime::common::PriceForParachainDelivery`
  pallets/xcmp-queue/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, T1-runtime

#3008 Companion for Polkadot#7617
  Cargo.lock
  client/relay-chain-inprocess-interface/src/lib.rs
  test/service/src/lib.rs
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#3007 Revert "companion for 14754: cli: move no-beefy flag to sc-cli (#2996)"
  Cargo.lock
  client/cli/src/lib.rs
  client/relay-chain-inprocess-interface/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  test/service/src/cli.rs
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low

#2952 set-metadata is a safe call
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
Labels: A0-please_review, B1-note_worthy, C1-low, T1-runtime, D3-trivial 🧸

#2924 additional turboflakes bridge-hub bootnodes
  parachains/chain-specs/bridge-hub-polkadot.json
  parachains/chain-specs/bridge-hub-westend.json
Labels: A2-insubstantial, B0-silent, C1-low, D3-trivial 🧸

#2875 Rename squatted crates
  parachains/pallets/parachain-info/Cargo.toml
Labels: B1-note_worthy, C1-low, T2-API, D2-notlive 💤

#2927 Add Helikon boot nodes for Bridge Hub Polkadot and Bridge Hub Westend.
  parachains/chain-specs/bridge-hub-polkadot.json
  parachains/chain-specs/bridge-hub-westend.json
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2951 nit: diff minimisation between asset hub runtimes
  parachain-template/runtime/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  test/runtime/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3013 exclude polkadot-parachain.asc and .sha256 from .dockerignore
  .dockerignore
  .github/workflows/release-50_docker-manual.yml
  .github/workflows/release-50_docker.yml
  docker/injected.Dockerfile
  docker/scripts/build-injected-image.sh
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3017 [Backport] Fix for the docker image creation from release branch (#3013)
  .dockerignore
  .github/workflows/release-50_docker-manual.yml
  .github/workflows/release-50_docker.yml
  docker/injected.Dockerfile
  docker/scripts/build-injected-image.sh
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#3019 [Backport] Fix release notes generation (#2868)
  scripts/ci/changelog/bin/changelog
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#3006 Remove `as_derivative` from `SafeCallFilter`
  client/pov-recovery/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
  parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Labels: B0-silent, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#2975 Revert "[Substrate companion] update libp2p to 0.52.0 (#2838)"
  Cargo.lock
  client/consensus/aura/Cargo.toml
  client/relay-chain-minimal-node/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3022 Bridges subtree sync
  Cargo.lock
  bridges/bin/runtime-common/Cargo.toml
  bridges/bin/runtime-common/src/messages_call_ext.rs
  bridges/bin/runtime-common/src/messages_xcm_extension.rs
  bridges/bin/runtime-common/src/mock.rs
  bridges/bin/runtime-common/src/refund_relayer_extension.rs
  bridges/modules/grandpa/src/lib.rs
  bridges/modules/messages/src/lib.rs
  bridges/modules/messages/src/mock.rs
  bridges/modules/parachains/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/Cargo.toml
  bridges/modules/xcm-bridge-hub-router/src/benchmarking.rs
  bridges/modules/xcm-bridge-hub-router/src/lib.rs
  bridges/modules/xcm-bridge-hub-router/src/mock.rs
  bridges/modules/xcm-bridge-hub-router/src/weights.rs
  bridges/primitives/chain-asset-hub-kusama/Cargo.toml
  bridges/primitives/chain-asset-hub-kusama/src/lib.rs
  bridges/primitives/chain-asset-hub-polkadot/Cargo.toml
  bridges/primitives/chain-asset-hub-polkadot/src/lib.rs
  bridges/primitives/header-chain/src/justification/mod.rs
  bridges/primitives/header-chain/src/justification/verification/equivocation.rs
  bridges/primitives/header-chain/src/justification/verification/mod.rs
  bridges/primitives/header-chain/src/justification/verification/optimizer.rs
  bridges/primitives/header-chain/src/justification/verification/strict.rs
  bridges/primitives/header-chain/src/lib.rs
  bridges/primitives/header-chain/tests/implementation_match.rs
  bridges/primitives/header-chain/tests/justification/equivocation.rs
  bridges/primitives/header-chain/tests/justification/optimizer.rs
  bridges/primitives/header-chain/tests/justification/strict.rs
  bridges/primitives/messages/src/lib.rs
  bridges/primitives/messages/src/source_chain.rs
  bridges/primitives/messages/src/target_chain.rs
  bridges/primitives/runtime/src/chain.rs
  bridges/primitives/test-utils/src/keyring.rs
  bridges/primitives/xcm-bridge-hub-router/Cargo.toml
  bridges/primitives/xcm-bridge-hub-router/src/lib.rs
  bridges/scripts/verify-pallets-build.sh
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2923 Companion for Substrate#14612
  Cargo.lock
  client/collator/src/lib.rs
  client/consensus/aura/src/collator.rs
  client/consensus/aura/src/collators/basic.rs
  client/consensus/aura/src/collators/lookahead.rs
  client/consensus/aura/src/equivocation_import_queue.rs
  client/consensus/aura/src/import_queue.rs
  client/consensus/aura/src/lib.rs
  client/consensus/common/src/import_queue.rs
  client/consensus/common/src/lib.rs
  client/consensus/proposer/src/lib.rs
  client/consensus/relay-chain/src/import_queue.rs
  client/consensus/relay-chain/src/lib.rs
  pallets/parachain-system/src/validate_block/implementation.rs
  parachain-template/node/src/service.rs
  polkadot-parachain/src/service.rs
  test/relay-sproof-builder/Cargo.toml
  test/relay-sproof-builder/src/lib.rs
  test/service/Cargo.toml
  test/service/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3031 xcm-emulator nits
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/hrmp_channels.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/send.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/hrmp_channels.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/send.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/send.rs
  parachains/integration-tests/emulated/common/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2731 Add set_current_relay_chain_state method for benchmarks
  pallets/parachain-system/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#2935 Added Asset Conversion in Kusama
  Cargo.lock
  parachains/integration-tests/emulated/assets/asset-hub-kusama/Cargo.toml
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/lib.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/mod.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/swap.rs
  parachains/integration-tests/emulated/common/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/mod.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_asset_conversion.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_assets_foreign.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_assets_local.rs
  parachains/runtimes/assets/asset-hub-kusama/src/weights/pallet_assets_pool.rs
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
Labels: A0-please_review, B1-note_worthy, C5-high, T1-runtime, D2-notlive 💤

#2998 benchmark script: remove file name for --output argument
  scripts/benchmarks-ci.sh
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3038 Companion for substrate#14776
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3039 Companion: restructure `benchmarking` macro related exports
  Cargo.lock
  parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/Cargo.toml
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/Cargo.toml
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
Labels: A2-insubstantial, B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3021 Companion for polkadot#7591: Add BEEFY capabilities to Westend and Kusama
  Cargo.lock
  parachains/integration-tests/emulated/common/src/constants.rs
Labels: B0-silent, A0-please_review, A4-companion, C1-low

#3018 [Backport] version bumps 10000
  Cargo.lock
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/glutton/glutton-kusama/src/lib.rs
  parachains/runtimes/starters/seedling/src/lib.rs
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
  polkadot-parachain/Cargo.toml
Labels: B0-silent, A0-please_review, A6-backport, C1-low, D3-trivial 🧸

#2270 Allow integrated relay chain light client
  Cargo.lock
  README.md
  client/cli/src/lib.rs
  client/relay-chain-minimal-node/Cargo.toml
  client/relay-chain-minimal-node/src/lib.rs
  client/relay-chain-rpc-interface/Cargo.toml
  client/relay-chain-rpc-interface/src/lib.rs
  client/relay-chain-rpc-interface/src/light_client_worker.rs
  client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
  client/relay-chain-rpc-interface/src/rpc_client.rs
  client/relay-chain-rpc-interface/src/tokio_platform.rs
  client/service/src/lib.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/src/command.rs
  test/service/src/lib.rs
  zombienet/tests/0002-pov_recovery.toml
  zombienet/tests/0002-pov_recovery.zndsl
  zombienet/tests/0003-full_node_catching_up.toml
  zombienet/tests/0003-full_node_catching_up.zndsl
  zombienet/tests/0007-full_node_warp_sync.toml
  zombienet/tests/0007-full_node_warp_sync.zndsl
Labels: A0-please_review, B1-note_worthy, C1-low, T0-node, D3-trivial 🧸

#3036 Companion for: contracts: Expose environment types for offchain tooling
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: B0-silent, A4-companion, C1-low, D3-trivial 🧸

#3046 Fix CI check and remove try-runtime command
  Cargo.lock
  parachain-template/node/Cargo.toml
  parachain-template/node/src/cli.rs
  parachain-template/node/src/command.rs
  polkadot-parachain/Cargo.toml
  polkadot-parachain/src/cli.rs
  polkadot-parachain/src/command.rs
  scripts/ci/gitlab/pipeline/test.yml
Labels: A0-please_review, B1-note_worthy, C1-low, T0-node, D3-trivial 🧸

#3044 Assets `force_set_metadata` is Safe
  parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
  parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
Labels: B0-silent, A0-please_review, C1-low, T1-runtime, D3-trivial 🧸

#3035 Contracts: Update Config::Debug
  Cargo.lock
  parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
Labels: B0-silent, A4-companion, C1-low, D3-trivial 🧸

#3045 Refactor docker image build
  .github/workflows/release-50_docker-manual.yml
  .github/workflows/release-50_docker.yml
  .github/workflows/release-50_publish-docker.yml
  docker/injected.Dockerfile
  docker/scripts/build-injected-image.sh
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3056 Add missing workspace members
  Cargo.lock
  Cargo.toml
  bridges/primitives/chain-asset-hub-polkadot/Cargo.toml
  bridges/primitives/chain-bridge-hub-kusama/Cargo.toml
  bridges/primitives/chain-bridge-hub-polkadot/Cargo.toml
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3055 Companion for polkadot/7659
  Cargo.lock
  pallets/parachain-system/src/lib.rs
  test/relay-sproof-builder/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3057 Fix experimental `aura` config and comment tests
  pallets/collator-selection/Cargo.toml
  pallets/collator-selection/src/mock.rs
  parachain-template/runtime/Cargo.toml
  parachain-template/runtime/src/lib.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/hrmp_channels.rs
  parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/hrmp_channels.rs
  parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/teleport.rs
  parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/teleport.rs
  parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
  parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
  parachains/runtimes/assets/asset-hub-polkadot/Cargo.toml
  parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
  parachains/runtimes/assets/asset-hub-westend/Cargo.toml
  parachains/runtimes/assets/asset-hub-westend/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
  parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
  parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
  parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
  parachains/runtimes/contracts/contracts-rococo/Cargo.toml
  parachains/runtimes/contracts/contracts-rococo/src/lib.rs
  parachains/runtimes/testing/penpal/Cargo.toml
  parachains/runtimes/testing/penpal/src/lib.rs
  parachains/runtimes/testing/rococo-parachain/Cargo.toml
  parachains/runtimes/testing/rococo-parachain/src/lib.rs
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸

#3049 update readme: archived repo
  README.md
Labels: A2-insubstantial, B0-silent, C1-low, D2-notlive 💤

#3051 Update to latest Substrate and Polkadot
  Cargo.lock
Labels: B0-silent, A0-please_review, C1-low, D3-trivial 🧸
